import fs from 'fs';
import path from 'path';

const messagesDir = path.resolve('messages');

// Read existing vi.json and en.json
const viPath = path.join(messagesDir, 'vi.json');
const enPath = path.join(messagesDir, 'en.json');

const viCurrent = JSON.parse(fs.readFileSync(viPath, 'utf-8'));
const enCurrent = JSON.parse(fs.readFileSync(enPath, 'utf-8'));

// Define new Vietnamese keys
const viNew: Record<string, string> = {
  // Common / Navbar / General
  "navbar_announcement_company": "CÔNG TY TNHH CÔNG NGHỆ CREDITBIRD • Phần mềm, Kelvot ERP & Lemy Finest Tinh dầu",
  "navbar_tagline": "Kiến tạo giá trị cho bạn",
  "navbar_select_language": "Ngôn ngữ / Language",
  "navbar_call_hotline": "Hotline: 0932 640 968",

  // Hero Section
  "hero_option_label": "LỰA CHỌN",

  // Core Domains
  "domain_software_code": "_LĨNH VỰC 01 / PHẦN MỀM MAY ĐO",
  "domain_erp_code": "_LĨNH VỰC 02 / HỆ THỐNG KELVOT ERP",
  "domain_scent_code": "_LĨNH VỰC 03 / MARKETING MÙI HƯƠNG",
  "domain_erp_feat_1": "Quản lý Định mức BOM & Lệnh sản xuất (MO)",
  "domain_erp_feat_2": "Kho thông minh WMS & Quét mã Barcode/QR",
  "domain_erp_feat_3": "Sổ cái Kế toán chuẩn VAS (TT200) & IFRS",
  "domain_erp_feat_4": "Đối soát giá thành và tồn kho thời gian thực",
  "domain_erp_website": "Website Kelvot.com",
  "domain_scent_feat_1": "Máy khuếch tán để bàn cho phòng làm việc",
  "domain_scent_feat_2": "Hệ thống khuếch tán công nghiệp kết nối HVAC",
  "domain_scent_feat_3": "Tinh dầu thiên nhiên nguyên chất chuẩn COA / GC-MS",
  "domain_scent_feat_4": "Dịch vụ thuê máy & nạp tinh dầu định kỳ",
  "domain_scent_website": "Website LemyFinest.com",

  // Featured Showcase: Tab 1 (RustSale CRM)
  "showcase_tab1_badge": "GIAO DIỆN MINH HỌA / RUST NATIVE CRM",
  "showcase_tab1_title": "RustSale CRM — Hộp thư hội tụ Zalo, WhatsApp, Messenger",
  "showcase_tab1_desc": "Được viết bằng Rust Native tối ưu hiệu năng, RustSale CRM giải quyết bài toán tin nhắn tư vấn phân tán trên nhiều kênh và thất thoát khách hàng tiềm năng. Dữ liệu được mã hóa và lưu trữ trực tiếp trên thiết bị của doanh nghiệp.",
  "showcase_tab1_feat1": "Quản lý đồng thời nhiều tài khoản Zalo cá nhân & Zalo OA trên 1 màn hình",
  "showcase_tab1_feat2": "Tích hợp luồng trò chuyện WhatsApp B2B & Fanpage Messenger",
  "showcase_tab1_feat3": "Bộ lọc thẻ Lead, ghi chú lịch sử giao dịch và phân công nhân viên tư vấn",
  "showcase_tab1_btn_explore": "Khám phá RustSale CRM",
  "showcase_tab1_btn_custom": "Dịch vụ may đo phần mềm",
  "showcase_tab1_mockup_title": "RustSale Omnichannel Hub (Giao diện minh họa)",
  "showcase_tab1_mockup_connected": "ĐÃ KẾT NỐI 4 KÊNH",
  "showcase_tab1_mockup_col1_header": "HỘI THOẠI HỘI TỤ",
  "showcase_tab1_mockup_chat1_name": "[Zalo] Cty Thép An Phát",
  "showcase_tab1_mockup_chat1_preview": "Báo giá giúp lô hàng ống thép...",
  "showcase_tab1_mockup_chat2_name": "[WhatsApp] FDI Logistics",
  "showcase_tab1_mockup_chat2_preview": "Điều khoản hợp đồng đã duyệt.",
  "showcase_tab1_mockup_chat3_name": "[FB Page] Chuỗi Nhà Thuốc",
  "showcase_tab1_mockup_chat3_preview": "Tư vấn máy phun sảnh chờ...",
  "showcase_tab1_mockup_col2_header": "CÔNG TY THÉP AN PHÁT (ZALO B2B)",
  "showcase_tab1_mockup_badge_hot": "LEAD TIỀM NĂNG",
  "showcase_tab1_mockup_client_label": "Khách hàng:",
  "showcase_tab1_mockup_client_msg": "Bên em cần may đo phần mềm quản lý kho kết nối Barcode và kế toán, anh tư vấn giúp.",
  "showcase_tab1_mockup_cb_msg": "Dạ CreditBird có sẵn giải pháp Kelvot ERP chuyên sâu về định mức BOM và kho WMS Barcode, em gửi anh tài liệu qua Zalo nhé.",
  "showcase_tab1_mockup_local": "Xử lý dữ liệu nội bộ (Local)",
  "showcase_tab1_mockup_note": "* Giao diện minh họa tính năng; cấu hình thực tế tùy theo nhu cầu triển khai.",

  // Featured Showcase: Tab 2 (Kelvot ERP)
  "showcase_tab2_badge": "GIAO DIỆN MINH HỌA / KELVOT ERP",
  "showcase_tab2_title": "Kelvot ERP — Chuyên sâu cho nhà máy, kho bãi & kế toán VAS",
  "showcase_tab2_desc": "Giải pháp ERP được thiết kế theo đúng quy chuẩn kế toán Việt Nam (Thông tư 200/133) và giải quyết các bài toán của doanh nghiệp sản xuất: định mức hao hụt nguyên vật liệu, quản trị kho mã vạch và tính giá thành công đoạn.",
  "showcase_tab2_card1_title": "ĐỊNH MỨC BOM ĐA CẤP",
  "showcase_tab2_card1_desc": "Tự động bóc tách nguyên vật liệu phụ kiện cho từng lệnh sản xuất.",
  "showcase_tab2_card2_title": "QUẢN TRỊ KHO WMS",
  "showcase_tab2_card2_desc": "Quét mã Barcode kiểm soát tồn kho theo vị trí kệ, lô hàng, hạn sử dụng.",
  "showcase_tab2_card3_title": "KẾ TOÁN QUẢN TRỊ",
  "showcase_tab2_card3_desc": "Sổ cái hạch toán tự động, báo cáo doanh thu, chi phí và thuế.",
  "showcase_tab2_card4_title": "KẾT NỐI MỞ API",
  "showcase_tab2_card4_desc": "Tích hợp hóa đơn điện tử, ngân hàng và sàn thương mại điện tử.",
  "showcase_tab2_btn_details": "Chi tiết giải pháp Kelvot ERP",
  "showcase_tab2_btn_website": "Website Kelvot.com",
  "showcase_tab2_table_title": "[GIAO DIỆN MINH HỌA] LỆNH SẢN XUẤT: MO-2026-089",
  "showcase_tab2_table_status": "ĐANG THỰC THI",
  "showcase_tab2_th_code": "MÃ VẬT TƯ",
  "showcase_tab2_th_name": "TÊN NGUYÊN LIỆU",
  "showcase_tab2_th_norm": "ĐỊNH MỨC",
  "showcase_tab2_th_actual": "THỰC XUẤT",
  "showcase_tab2_th_status": "TRẠNG THÁI",
  "showcase_tab2_row1_name": "Thép lá cán nguội 1.2mm",
  "showcase_tab2_row2_name": "Dây đồng kỹ thuật phi 0.8",
  "showcase_tab2_row3_name": "Bu-lông đai ốc M6x20 Inox",
  "showcase_tab2_row_unit_kg": "kg",
  "showcase_tab2_row_unit_pcs": "con",
  "showcase_tab2_status_complete": "ĐỦ 100%",
  "showcase_tab2_journal_label": "Bút toán tự động hạch toán:",
  "showcase_tab2_journal_val": "Nợ TK 154 / Có TK 152 (Chuẩn VAS)",
  "showcase_tab2_table_note": "* Mô phỏng bảng tính định mức BOM; cấu hình thực tế được tùy biến theo quy trình của từng nhà máy.",

  // Featured Showcase: Tab 3 (Scent & Lemy Finest)
  "showcase_tab3_badge": "THIẾT BỊ HƯƠNG THƠM & TINH DẦU / LEMYFINEST.COM",
  "showcase_tab3_title": "Sản phẩm tinh dầu & thiết bị máy phun Lemy Finest",
  "showcase_tab3_desc": "CreditBird cung cấp cả 2 dòng sản phẩm chủ lực: Thiết bị máy phun khuếch tán (để bàn và kết nối điều hòa HVAC) cùng tinh dầu thiên nhiên có hồ sơ kiểm định COA và phân tích GC-MS theo từng mã sản phẩm.",
  "showcase_tab3_policy_title": "Chính sách cung ứng & dịch vụ:",
  "showcase_tab3_policy_item1_label": "Mua trọn bộ thiết bị:",
  "showcase_tab3_policy_item1_val": "Bảo hành chính hãng theo hợp đồng và từng gói thiết bị.",
  "showcase_tab3_policy_item2_label": "Thuê máy & nạp dầu định kỳ:",
  "showcase_tab3_policy_item2_val": "Khảo sát thể tích thực tế, lắp đặt và định kỳ kiểm tra máy, nạp thêm tinh dầu theo thỏa thuận.",
  "showcase_tab3_policy_item3_label": "Cung cấp tinh dầu sỉ & lẻ:",
  "showcase_tab3_policy_item3_val": "Can 500ml, 1.000ml hoặc chai 50ml, 100ml tùy chọn.",
  "showcase_tab3_btn_consult": "Nhận tư vấn thiết bị & tinh dầu",
  "showcase_tab3_btn_details": "Chi tiết giải pháp Scent",
  "showcase_tab3_card1_badge": "THIẾT BỊ MÁY PHUN",
  "showcase_tab3_card1_tag": "2 DÒNG MÁY",
  "showcase_tab3_card1_title": "Máy khuếch tán công nghệ sương nano",
  "showcase_tab3_card1_item1_label": "1. Dòng máy để bàn:",
  "showcase_tab3_card1_item1_desc": "Phù hợp phòng làm việc, phòng họp, spa và gia đình. Diện tích sử dụng tham khảo: 30–80 m², tùy model và điều kiện không gian.",
  "showcase_tab3_card1_item2_label": "2. Dòng máy kết nối HVAC:",
  "showcase_tab3_card1_item2_desc": "Phù hợp sảnh lớn, tòa nhà, showroom và khách sạn. Độ phủ tham khảo 500 - 5.000 m² (khảo sát lưu lượng gió và thể tích m³ thực tế để chọn công suất phù hợp).",
  "showcase_tab3_card1_note": "* Thông số kỹ thuật cụ thể và cam kết độ phủ đối chiếu theo hồ sơ kiểm thử của từng thiết bị.",
  "showcase_tab3_card1_link": "Xem thông số các dòng máy phun",
  "showcase_tab3_card2_badge": "TINH DẦU COA",
  "showcase_tab3_card2_tag": "KIỂM ĐỊNH COA",
  "showcase_tab3_card2_title": "Bộ sưu tập mùi hương chuẩn kiểm nghiệm",
  "showcase_tab3_card2_item1_label": "Nốt hương phổ biến:",
  "showcase_tab3_card2_item1_desc": "Cam ngọt (Sweet Orange), Sả chanh (Lemongrass), Trà trắng (White Tea), Trầm hương (Oud Wood), Lavender Pháp.",
  "showcase_tab3_card2_item2_label": "Kiểm định & an toàn:",
  "showcase_tab3_card2_item2_desc": "Từng mã sản phẩm tinh dầu có phiếu kiểm nghiệm COA và phân tích GC-MS đối chiếu thành phần theo hồ sơ kỹ thuật riêng.",
  "showcase_tab3_card2_item3_label": "Quy cách đóng gói:",
  "showcase_tab3_card2_item3_desc": "Chai 50ml, 100ml cho cá nhân & Can 500ml, 1.000ml cho máy công nghiệp.",
  "showcase_tab3_card2_note": "* Hình ảnh thực tế và chứng chỉ COA được cung cấp đầy đủ khi tư vấn và bàn giao.",
  "showcase_tab3_card2_link": "Xem danh mục bảng mùi hương",

  // How We Work Section
  "workflow_tech_tag": "QUY TRÌNH KỸ THUẬT",
  "workflow_tech_title": "1. Phát triển phần mềm & Kelvot ERP",
  "workflow_tech_step1_title": "Khảo sát & lập kiến trúc",
  "workflow_tech_step1_desc": "Phân tích chi tiết quy trình nghiệp vụ hiện tại của doanh nghiệp, tư vấn giải pháp kỹ thuật, lập bản đặc tả chức năng và ký kết hợp đồng B2B kèm cam kết bảo mật NDA.",
  "workflow_tech_step2_title": "Thiết kế & phát triển theo từng giai đoạn",
  "workflow_tech_step2_desc": "Chia dự án thành các giai đoạn ngắn, kiểm thử thường xuyên và cập nhật tiến độ để khách hàng xem, góp ý từng tính năng.",
  "workflow_tech_step3_title": "Kiểm thử nghiệm thu & hướng dẫn sử dụng",
  "workflow_tech_step3_desc": "Cùng khách hàng kiểm thử theo yêu cầu đã thống nhất, hướng dẫn sử dụng và chuyển dữ liệu sang hệ thống mới theo kế hoạch triển khai.",
  "workflow_tech_step4_title": "Bàn giao mã nguồn & bảo hành kỹ thuật",
  "workflow_tech_step4_desc": "Bàn giao đầy đủ quyền sở hữu kho mã nguồn (cho các dự án phát triển may đo), tài liệu kỹ thuật và chính sách bảo hành 12 - 24 tháng theo phạm vi hợp đồng.",
  "workflow_scent_tag": "QUY TRÌNH HƯƠNG THƠM",
  "workflow_scent_title": "2. Dịch vụ Scent Marketing & Máy phun",
  "workflow_scent_step1_title": "Khảo sát thể tích & luồng gió",
  "workflow_scent_step1_desc": "Đo đạc diện tích mặt sàn (m²) và chiều cao trần (m). Khảo sát cấu trúc luồng gió tự nhiên hoặc hệ thống ống gió điều hòa trung tâm HVAC.",
  "workflow_scent_step2_title": "Thử mẫu hương & chọn thiết bị",
  "workflow_scent_step2_desc": "Mang mẫu trực tiếp các dòng tinh dầu thiên nhiên có kiểm định COA cho khách hàng trải nghiệm thực tế; lựa chọn dòng máy để bàn hoặc máy công nghiệp phù hợp.",
  "workflow_scent_step3_title": "Lắp đặt & cài đặt phun tự động",
  "workflow_scent_step3_desc": "Kỹ thuật viên lắp đặt an toàn, thẩm mỹ. Cài đặt hẹn giờ bật/tắt và điều chỉnh nồng độ phun sương nano theo khung giờ hoạt động của doanh nghiệp.",
  "workflow_scent_step4_title": "Bảo dưỡng & nạp dầu định kỳ",
  "workflow_scent_step4_desc": "Dịch vụ chăm sóc định kỳ: vệ sinh béc phun nano, kiểm tra máy và châm thêm tinh dầu tận nơi theo phạm vi hợp đồng hoặc gói dịch vụ khách hàng lựa chọn.",
  "workflow_cta_quote": "Đăng ký tư vấn quy trình triển khai",

  // Real Use Cases Section
  "usecases_label_problem": "Vấn đề thường gặp:",
  "usecases_label_solution": "Giải pháp của CreditBird:",
  "usecase_1_title": "Nhà máy sản xuất & xưởng gia công",
  "usecase_1_problem": "Khó kiểm soát định mức tiêu hao nguyên phụ liệu, sai lệch tồn kho giữa kế toán và thực tế.",
  "usecase_1_solution": "Ứng dụng Kelvot ERP quản lý định mức BOM đa cấp, xuất nhập kho quét mã Barcode và tự động hạch toán chi phí theo chuẩn VAS.",
  "usecase_1_link": "Chi tiết giải pháp ERP sản xuất",
  "usecase_2_title": "Doanh nghiệp thương mại & bán lẻ",
  "usecase_2_problem": "Tin nhắn tư vấn phân tán trên nhiều tài khoản Zalo và Fanpage khiến nhân viên dễ bỏ sót khách hàng.",
  "usecase_2_solution": "Trang bị phần mềm RustSale CRM gom Zalo, WhatsApp, Messenger về một màn hình máy tính tập trung, hỗ trợ gắn thẻ phân loại Lead, lưu lịch sử giao dịch và phân công nhân viên tư vấn kịp thời.",
  "usecase_2_link": "Tìm hiểu RustSale CRM",
  "usecase_3_title": "Khách sạn, resort, spa & showroom",
  "usecase_3_problem": "Không gian sảnh và phòng dịch vụ thiếu điểm nhấn trải nghiệm, mùi ẩm mốc hoặc mùi điều hòa.",
  "usecase_3_solution": "Lắp đặt máy khuếch tán nano Lemy Finest kết nối hệ thống điều hòa HVAC cùng các dòng tinh dầu thiên nhiên có kiểm định COA theo hồ sơ sản phẩm.",
  "usecase_3_link": "Xem giải pháp hương thơm HVAC",
  "usecase_4_title": "Doanh nghiệp cần phần mềm nội bộ may đo",
  "usecase_4_problem": "Phần mềm hiện có chưa đáp ứng đầy đủ quy trình riêng của doanh nghiệp.",
  "usecase_4_solution": "CreditBird may đo ứng dụng Web/App theo đúng bài toán đặc thù, bàn giao 100% source code sạch và cung ứng nhân sự IT Senior hỗ trợ vận hành theo hợp đồng.",
  "usecase_4_link": "Dịch vụ may đo phần mềm",

  // Footer
  "footer_custom_services": "DỊCH VỤ MAY ĐO",
  "footer_custom_web_app": "May đo Web & Mobile App theo yêu cầu",
  "footer_custom_microservices": "Kiến trúc Microservices, bàn giao 100% code",
  "footer_it_senior": "Cho thuê nhân sự IT Senior (Onsite/Remote)",
  "footer_github_repo": "Kho mã nguồn mở (GitHub)",
  "footer_facebook_page": "Fanpage chính thức (Facebook)",
  "footer_rustsale_products": "SẢN PHẨM RUSTSALE CRM",
  "footer_rustsale_inbox": "Hộp thư hội tụ Zalo, WhatsApp, Messenger",
  "footer_rustsale_keyring": "Bảo mật lưu trữ cục bộ Local Keyring",
  "footer_rustsale_notion": "Cẩm nang sử dụng toàn tập (Notion)",
  "footer_erp_modules": "PHÂN HỆ NGHIỆP VỤ",
  "footer_erp_bom": "Quản lý Định mức Sản xuất Multi-BOM",
  "footer_erp_wms": "Quản lý Kho WMS quét mã Barcode/QR",
  "footer_erp_vas": "Kế toán Quản trị chuẩn VAS (TT200) & IFRS",
  "footer_erp_cashflow": "Đối soát dòng tiền và tính giá thành tự động",
  "footer_erp_brand": "THƯƠNG HIỆU ĐỘC LẬP",
  "footer_erp_portal": "Cổng thông tin chính thức Kelvot.com",
  "footer_erp_license": "Đăng ký khảo sát & bản quyền triển khai",
  "footer_scent_brand": "LEMY FINEST TINH DẦU",
  "footer_scent_diffusers": "MÁY PHUN KHUẾCH TÁN NANO",
  "footer_scent_desktop": "Máy khuếch tán để bàn phòng làm việc",
  "footer_scent_hvac": "Máy công nghiệp kết nối điều hòa HVAC (500 - 5.000m²)",
  "footer_scent_leasing": "Dịch vụ thuê máy & nạp tinh dầu định kỳ",
  "footer_scent_warranty": "Bảo hành thiết bị theo hợp đồng & gói dịch vụ",
  "footer_scent_oils": "TINH DẦU THIÊN NHIÊN COA",
  "footer_scent_coa_desc": "Tinh dầu thiên nhiên có kiểm định COA / GC-MS",
  "footer_scent_scent_chart": "Bảng mùi hương cho Khách sạn, Spa, Showroom",
  "footer_scent_website": "Website chính thức LemyFinest.com",
  "footer_hotline_title": "HOTLINE & B2B",

  // Demo Modal
  "modal_err_required": "Vui lòng điền đầy đủ họ tên, số điện thoại và email.",
  "modal_err_generic": "Có lỗi xảy ra khi gửi thông tin. Quý khách vui lòng gọi Hotline 0932.640.968.",
  "modal_err_network": "Không thể kết nối máy chủ. Quý khách vui lòng gọi điện thoại trực tiếp hoặc chat Zalo.",

  // Subpage: Software
  "sw_page_title": "Viết Phần Mềm May Đo Theo Yêu Cầu — CreditBird (MST: 0315397327)",
  "sw_page_desc": "Dịch vụ phát triển phần mềm may đo doanh nghiệp, kiến trúc Microservices (Rust, Go, Python, SvelteKit). Bàn giao 100% full source code, cam kết SLA 99.9%.",
  "sw_hero_eyebrow": "_NGÀNH NGHỀ KINH DOANH CHÍNH / MST: 0315397327",
  "sw_hero_spec": "Microservices • 100% Full Source Code • Không Vendor Lock-in",
  "sw_hero_title": "Viết Phần Mềm Doanh Nghiệp May Đo Theo Yêu Cầu",
  "sw_hero_desc": "Cung cấp dịch vụ kiến trúc và phát triển phần mềm chuyên biệt theo đúng quy trình vận hành độc thù của doanh nghiệp. Cam kết bàn giao 100% mã nguồn sạch, bảo hành dài hạn và đồng hành chuyển đổi số bền vững.",
  "sw_hero_btn_primary": "Đăng Ký Tư Vấn Kiến Trúc Phần Mềm",
  "sw_hero_btn_secondary": "Xem Quy Trình 6 Bước",
  "sw_metrics_eyebrow": "_TIÊU CHUẨN KỸ THUẬT / ENGINEERING STANDARDS",
  "sw_metrics_title": "Cam kết chất lượng mã nguồn và độ ổn định cấp ngân hàng",
  "sw_metric1_label": "BÀN GIAO MÃ NGUỒN",
  "sw_metric1_val": "100% Full Code",
  "sw_metric1_sub": "Bàn giao trọn bộ Git repository, tài liệu API và sơ đồ kiến trúc",
  "sw_metric2_label": "KHẢ NĂNG CHỊU TẢI",
  "sw_metric2_val": "100k+ CCU",
  "sw_metric2_sub": "Kiến trúc High-Concurrency bằng Rust, Go và Microservices",
  "sw_metric3_label": "CAM KẾT VẬN HÀNH",
  "sw_metric3_val": "SLA 99.9%",
  "sw_metric3_sub": "Thời gian phản hồi ứng cứu sự cố khẩn cấp dưới 15 phút",
  "sw_metric4_label": "BẢO HÀNH KỸ THUẬT",
  "sw_metric4_val": "12 - 24 Tháng",
  "sw_metric4_sub": "Miễn phí vá lỗi bảo mật và hỗ trợ chuyển giao kỹ thuật tận tâm",
  "sw_pillar_eyebrow": "_6 TRỤ CỘT KỸ THUẬT / TECHNICAL PILLARS/",
  "sw_pillar_title": "Nền Tảng Công Nghệ Hiện Đại Dành Cho Doanh Nghiệp Tăng Trưởng",
  "sw_pillar_sub": "Xóa bỏ hoàn toàn nỗi lo phụ thuộc nhà cung cấp giải pháp với cam kết sở hữu 100% mã nguồn.",
  "sw_pillar_desc": "Chúng tôi áp dụng các tiêu chuẩn kiến trúc phần mềm tiên tiến nhất trên thế giới để đảm bảo hệ thống có thể chịu tải hàng chục ngàn người dùng đồng thời mà vẫn mượt mà.",
  "sw_pillar1_title": "Kiến trúc Microservices & AI-Ready",
  "sw_pillar1_desc": "Phát triển backend bằng Rust, Go và Python tối ưu hiệu năng bộ nhớ, tích hợp sẵn các pipeline AI Inference và Microservices chịu tải hàng triệu requests.",
  "sw_pillar2_title": "Bàn giao 100% Mã nguồn Sạch & Quyền sở hữu AI",
  "sw_pillar2_desc": "Doanh nghiệp sở hữu trọn vẹn toàn bộ mã nguồn Git, cơ sở dữ liệu, API specs và trọng số mô hình AI huấn luyện riêng. Không vendor lock-in.",
  "sw_pillar3_title": "Bảo mật Cấp Ngân hàng & Private AI",
  "sw_pillar3_desc": "Mã hóa dữ liệu tại chỗ (At-Rest) và trên đường truyền (In-Transit). Triển khai Private LLM On-Premise bảo mật tuyệt đối dữ liệu nội bộ doanh nghiệp.",
  "sw_pillar4_title": "Giao diện Web, App & Trợ lý AI Agent",
  "sw_pillar4_desc": "Ứng dụng SvelteKit, React và Flutter xây dựng trải nghiệm mượt mà, tích hợp giao diện hội thoại và trợ lý AI Agent tương tác thông minh theo ngữ cảnh.",
  "sw_pillar5_title": "Kết nối Core Banking & Tự động hóa Agentic",
  "sw_pillar5_desc": "Tích hợp liên thông tài khoản ngân hàng, VietQR, hạch toán đối soát tự động và các quy trình Agentic Workflows tự xử lý nghiệp vụ không cần can thiệp thủ công.",
  "sw_pillar6_title": "Cam kết SLA 99.9% & Tối ưu Mô hình Dài hạn",
  "sw_pillar6_desc": "Chính sách bảo hành kỹ thuật 12 - 24 tháng, cam kết đội ngũ kỹ sư hỗ trợ ứng cứu sự cố 24/7 với thời gian phản hồi dưới 15 phút và liên tục cập nhật công nghệ mới.",
  "sw_tech_eyebrow": "_CÔNG NGHỆ CHUYÊN SÂU / TECH STACK MATRIX/",
  "sw_tech_title": "Lựa Chọn Công Nghệ Tối Ưu Cho Từng Bài Toán",
  "sw_tech_sub": "Tập trung vào các ngôn ngữ hiện đại, hiệu năng bộ nhớ tối đa và an toàn kiểu dữ liệu.",
  "sw_tech_desc": "Mỗi dự án được thiết kế với sự kết hợp công nghệ phù hợp nhất để tối đa hóa tốc độ phản hồi và giảm thiểu chi phí máy chủ hàng tháng.",
  "sw_tech1_title": "Hệ Thống Backend Siêu Tốc",
  "sw_tech1_desc": "Rust, Golang, Python, Node.js kết hợp Microservices hiệu năng cao, tối ưu hóa xử lý đồng thời cực lớn.",
  "sw_tech2_title": "Trí Tuệ Nhân Tạo & AI Agents",
  "sw_tech2_desc": "Tích hợp OpenAI/Claude/Llama, Private LLM On-Premise, RAG tra cứu tri thức nội bộ và Agentic Workflows tự động xử lý quy trình nghiệp vụ.",
  "sw_tech3_title": "Frontend Web Ứng Dụng",
  "sw_tech3_desc": "SvelteKit, React, Tailwind CSS, TypeScript tối ưu hóa SSR/SSG cho trải nghiệm người dùng mượt mà tức thì.",
  "sw_tech4_title": "Ứng Dụng Di Động Đa Nền Tảng",
  "sw_tech4_desc": "Flutter, React Native, Swift và Kotlin Native cho trải nghiệm giao diện mượt mà 120Hz trên iOS và Android.",
  "sw_tech5_title": "Cơ Sở Dữ Liệu & Vector Search",
  "sw_tech5_desc": "PostgreSQL, ScyllaDB, Redis, Kafka phân tán cùng Qdrant / pgvector cho tìm kiếm ngữ nghĩa và lưu trữ vector embeddings.",
  "sw_tech6_title": "Hạ Tầng Tự Động & AI Cluster",
  "sw_tech6_desc": "Docker, Kubernetes, GPU Inference Clusters, Terraform, AWS, GCP và CI/CD tự động hóa kiểm thử liên tục.",
  "sw_roadmap_badge": "_LỘ TRÌNH TRIỂN KHAI / 6-STEP ROADMAP/",
  "sw_roadmap_title": "Quy Trình Phát Triển Phần Mềm Minh Bạch Từ Đầu Đến Cuối",
  "sw_roadmap_desc": "Áp dụng quy trình Agile/Scrum linh hoạt với các mốc nghiệm thu rõ ràng, giúp khách hàng luôn kiểm soát được tiến độ và chất lượng sản phẩm.",
  "sw_step1_title": "Khảo sát, Đặc tả (SRS) & Khả thi AI",
  "sw_step1_desc": "Phân tích quy trình nghiệp vụ thực tế, đánh giá tính khả thi ứng dụng AI, xây dựng sơ đồ luồng dữ liệu và tài liệu kiến trúc chi tiết.",
  "sw_step2_title": "Thiết kế Kiến trúc & UX/UI Bản mẫu",
  "sw_step2_desc": "Thiết kế giao diện chuẩn Design System, thiết kế luồng tương tác AI Agent, chốt tiêu chuẩn bảo mật và API Schema.",
  "sw_step3_title": "Lập trình Agile & Tăng tốc với AI Pair",
  "sw_step3_desc": "Chia nhỏ tính năng theo các sprint 2 tuần, ứng dụng AI-Augmented Development tăng tốc tiến độ gấp 2x kèm CI/CD kiểm thử liên tục.",
  "sw_step4_title": "Kiểm thử Tự động, Pentest & Rà soát AI",
  "sw_step4_desc": "Stress test chịu tải cao, kiểm tra lỗ hổng OWASP Top 10, đo lường độ chính xác và an toàn của các phân hệ AI/RAG.",
  "sw_step5_title": "Bàn giao Source Code & Triển khai Cloud",
  "sw_step5_desc": "Bàn giao 100% Git repository, Docker container, kịch bản triển khai Kubernetes và tài liệu chuyển giao vận hành.",
  "sw_step6_title": "Bảo hành, SLA 24/7 & Nâng cấp AI",
  "sw_step6_desc": "Bảo trì hệ thống toàn diện, giám sát hiệu năng qua Prometheus/Grafana và đồng hành nâng cấp mô hình AI định kỳ.",
  "sw_cta_eyebrow": "_KHỞI TẠO DỰ ÁN PHẦN MỀM/",
  "sw_cta_title": "Hiện Thực Hóa Ý Tưởng Phần Mềm Với Chuẩn Mực Kỹ Thuật Cao Nhất",
  "sw_cta_desc": "Đội ngũ kiến trúc sư giải pháp của CreditBird sẵn sàng lắng nghe bài toán nghiệp vụ của bạn để tư vấn kiến trúc tối ưu nhất ngay từ ngày đầu tiên.",
  "sw_cta_btn": "Đăng Ký Tư Vấn & Nhận Bản Phân Tích Kỹ Thuật",

  // Subpage: ERP
  "erp_page_title": "Kelvot ERP — Hệ Thống ERP Sản Xuất, Kho Bãi & Kế Toán Quản Trị | CreditBird",
  "erp_page_desc": "Kelvot ERP (kelvot.com) — Hệ thống ERP may đo chuyên sâu cho sản xuất định mức BOM, quản lý kho WMS và kế toán tài chính VAS/IFRS. Phát triển bởi CreditBird.",
  "erp_hero_eyebrow": "_THƯƠNG HIỆU ERP ĐỘC LẬP / KELVOT.COM",
  "erp_hero_spec": "Định Mức BOM • Kho WMS • Kế Toán VAS/IFRS",
  "erp_hero_title": "Kelvot ERP — Quản Trị Toàn Diện Sản Xuất, Kho & Tài Chính",
  "erp_hero_desc": "Thương hiệu phần mềm ERP chuyên sâu trực thuộc hệ sinh thái CreditBird. Được kiến trúc may đo dành riêng cho các nhà máy sản xuất, chuỗi bán lẻ và tập đoàn phân phối cần kiểm soát dòng tiền và chi phí sản xuất theo thời gian thực.",
  "erp_hero_btn_primary": "Truy Cập Website Kelvot.com",
  "erp_hero_btn_secondary": "Đăng Ký Khảo Sát & Demo ERP",
  "erp_metrics_eyebrow": "_CHỈ SỐ THỰC CHỨNG / PRODUCTION METRICS",
  "erp_metrics_title": "Tiêu chuẩn kiểm soát chất lượng và tối ưu hóa chi phí vận hành",
  "erp_metric1_label": "ĐỊNH MỨC SẢN XUẤT",
  "erp_metric1_val": "Multi-BOM",
  "erp_metric1_sub": "Kiểm soát chi tiết định mức hao hụt nguyên phụ liệu đa cấp",
  "erp_metric2_label": "ĐỘ CHÍNH XÁC KHO",
  "erp_metric2_val": "99.8%",
  "erp_metric2_sub": "Nhận diện quét mã Barcode/QR vị trí ô kệ không sai sót",
  "erp_metric3_label": "BÁO CÁO TÀI CHÍNH",
  "erp_metric3_val": "Thời gian thực",
  "erp_metric3_sub": "Tự động kết chuyển chi phí và hạch toán dòng tiền cuối kỳ",
  "erp_metric4_label": "CHUẨN MỰC HẠCH TOÁN",
  "erp_metric4_val": "VAS & IFRS",
  "erp_metric4_sub": "Tuân thủ nghiêm Thông tư 200/133 và chuẩn mực quốc tế",
  "erp_modules_eyebrow": "_PHÂN HỆ TRỌNG YẾU / CORE MODULES/",
  "erp_modules_title": "Kiến Trúc ERP Khép Kín Cho Doanh Nghiệp Sản Xuất & Thương Mại",
  "erp_modules_sub": "Khả năng module hóa cao độ, triển khai độc lập hoặc đồng bộ liên thông toàn diện.",
  "erp_modules_desc": "Mỗi phân hệ của Kelvot ERP được thiết kế theo chuẩn microservices độc lập, đảm bảo dữ liệu kế toán tài chính, kho vận và kế hoạch sản xuất đồng bộ tức thì.",
  "erp_mod1_title": "Quản Trị Sản Xuất & Định Mức BOM Đa Cấp",
  "erp_mod1_desc": "Thiết lập cây định mức nguyên vật liệu (Multi-level Bill of Materials), tính toán nhu cầu nguyên vật liệu (MRP) và phân bổ chi phí sản xuất theo từng công đoạn chuyền.",
  "erp_mod2_title": "Quản Lý Kho Bãi Thông Minh (WMS)",
  "erp_mod2_desc": "Quản lý theo vị trí ô kệ (Bin location), kiểm soát hạn sử dụng (FIFO/FEFO), quản lý theo số Lô (Batch number) và kiểm đếm bằng Barcode/QR code.",
  "erp_mod3_title": "Kế Toán Quản Trị Chuẩn VAS & IFRS",
  "erp_mod3_desc": "Tuân thủ nghiêm ngặt Thông tư 200/133 của Bộ Tài chính và chuẩn mực quốc tế IFRS. Tự động sinh bút toán kép từ các nghiệp vụ kho, mua sắm và bán hàng.",
  "erp_mod4_title": "Chuỗi Cung Ứng & Mua Hàng Tập Trung",
  "erp_mod4_desc": "Quy trình phê duyệt báo giá đa cấp bậc, theo dõi trạng thái đơn mua hàng (PO), đánh giá năng lực nhà cung cấp và quản lý thời hạn công nợ chi tiết.",
  "erp_mod5_title": "Quản Trị Kênh Phân Phối & Bán Hàng",
  "erp_mod5_desc": "Thiết lập ma trận chính sách giá linh hoạt theo cấp đại lý, khu vực địa lý, hạn mức tín dụng và tự động tính chiết khấu thương mại theo doanh số.",
  "erp_mod6_title": "Đối Soát Tự Động & Hóa Đơn Điện Tử",
  "erp_mod6_desc": "Kết nối liên thông ngân hàng (Bank Hub), tự động đối soát sổ phụ với số dư thực tế, tích hợp trực tiếp các nhà cấp hóa đơn điện tử hợp chuẩn.",
  "erp_split_eyebrow": "_SẢN XUẤT THỰC CHIẾN / BOM & MRP",
  "erp_split_title": "Kiểm Soát Từng Gram Nguyên Liệu & Giây Máy Chạy",
  "erp_split_desc": "Khắc phục triệt để tình trạng thiếu hụt nguyên vật liệu làm đình trệ đơn hàng hoặc tồn kho nguyên phụ liệu quá mức gây đọng vốn lưu động.",
  "erp_split_link": "Tìm hiểu thêm tài liệu kỹ thuật tại Kelvot.com",
  "erp_bullet1_title": "Định mức hao hụt động",
  "erp_bullet1_text": "Tự động tính toán tỷ lệ hao hụt nguyên vật liệu theo từng lô máy móc và tay nghề nhân công.",
  "erp_bullet2_title": "Lập kế hoạch mua hàng MRP tự động",
  "erp_bullet2_text": "Đối chiếu tồn kho khả dụng để tự sinh đơn mua hàng PO trước khi chuyền sản xuất bị gián đoạn.",
  "erp_bullet3_title": "Tính giá thành đích danh thời gian thực",
  "erp_bullet3_text": "Phân bổ chính xác 3 yếu tố giá thành: Chi phí NVL trực tiếp, chi phí nhân công và chi phí sản xuất chung.",
  "erp_cta_eyebrow": "_TƯ VẤN TRIỂN KHAI KELVOT ERP/",
  "erp_cta_title": "Chuẩn Hóa Toàn Bộ Quy Trình Vận Hành Doanh Nghiệp",
  "erp_cta_desc": "Đội ngũ chuyên gia ERP của Kelvot và CreditBird sẵn sàng đến tận nhà máy của bạn để khảo sát quy trình, tư vấn giải pháp và xây dựng lộ trình số hóa chi tiết.",
  "erp_cta_btn_primary": "Đăng Ký Khảo Sát Nhà Máy & Báo Giá",
  "erp_cta_btn_secondary": "Khám Phá Website Kelvot.com",

  // Subpage: IT Staffing
  "it_page_title": "Cho Thuê Nhân Sự IT Cho Doanh Nghiệp — CreditBird (MST: 0315397327)",
  "it_page_desc": "Dịch vụ cho thuê kỹ sư CNTT chất lượng cao Onsite & Dedicated Team. Senior Devs (Rust, Go, Python, SvelteKit, DevOps). Onboarding trong 48h, cam kết NDA bảo mật tuyệt đối.",
  "it_hero_eyebrow": "_NGÀNH NGHỀ KINH DOANH CHÍNH / MST: 0315397327",
  "it_hero_spec": "Onsite & Dedicated Squad • Onboarding 48h • Cam kết NDA",
  "it_hero_title": "Cho Thuê Nhân Sự IT Chất Lượng Cao Cho Doanh Nghiệp",
  "it_hero_desc": "Giải quyết triệt để bài toán khan hiếm nhân lực kỹ thuật cấp cao. Cung cấp kỹ sư Senior phần mềm, DevOps và kiến trúc sư hệ thống làm việc Onsite tại văn phòng hoặc Dedicated Remote Team với chi phí tối ưu và pháp lý minh bạch.",
  "it_hero_btn_primary": "Yêu Cầu Hồ Sơ & Báo Giá Kỹ Sư",
  "it_hero_btn_secondary": "Xem Quy Trình Onboard 48H",
  "it_metrics_eyebrow": "_CHỈ SỐ CAM KẾT DỊCH VỤ / SLA METRICS",
  "it_metrics_title": "Tiêu chuẩn tuyển chọn khắt khe và bảo đảm tiến độ dự án",
  "it_metric1_label": "THỜI GIAN SÀNG LỌC",
  "it_metric1_val": "48 Giờ",
  "it_metric1_sub": "Nhận danh sách CV ứng viên phù hợp với bài toán kỹ thuật",
  "it_metric2_label": "THỬ VIỆC THỰC TẾ",
  "it_metric2_val": "14 Ngày",
  "it_metric2_sub": "Đánh giá năng lực trực tiếp trong sprint, đổi người 100% miễn phí",
  "it_metric3_label": "KINH NGHIỆM KỸ SƯ",
  "it_metric3_val": "4 - 8 Năm",
  "it_metric3_sub": "Kỹ sư Senior có năng lực giải quyết sự cố và tối ưu kiến trúc",
  "it_metric4_label": "PHÁP LÝ & HÓA ĐƠN",
  "it_metric4_val": "Hợp Đồng B2B",
  "it_metric4_sub": "Xuất hóa đơn VAT đầy đủ (MST: 0315397327) và bảo mật NDA",
  "it_models_eyebrow": "_MÔ HÌNH HỢP TÁC LINH HOẠT / COOPERATION MODELS/",
  "it_models_title": "Phương Thức Cung Ứng Nhân Sự Theo Nhu Cầu Doanh Nghiệp",
  "it_models_sub": "Linh hoạt mở rộng hoặc thu hẹp quy mô đội ngũ theo từng giai đoạn phát triển dự án.",
  "it_models_desc": "Từ việc bổ sung kỹ sư làm việc tại văn phòng của bạn đến việc thiết lập một trung tâm công nghệ chuyên trách từ xa (Offshore Development Center - ODC).",
  "it_model1_title": "Kỹ sư IT Làm việc Onsite tại Doanh nghiệp",
  "it_model1_desc": "Nhân sự làm việc trực tiếp tại trụ sở văn phòng khách hàng. Doanh nghiệp trực tiếp quản lý, giao việc và điều phối theo văn hóa nội bộ.",
  "it_model2_title": "Biệt đội Kỹ thuật Chuyên trách Từ xa",
  "it_model2_desc": "Đội ngũ kỹ sư làm việc full-time độc quyền cho dự án của bạn, có kèm Tech Lead và Scrum Master hỗ trợ quản trị chất lượng mã nguồn.",
  "it_model3_title": "Tăng cường Kỹ sư Ngắn hạn theo Dự án",
  "it_model3_desc": "Bổ sung nhanh chóng các vị trí kỹ thuật cấp thiết trong các đợt chạy tiến độ (Go-Live, phát hành sản phẩm mới, kiểm toán hệ thống).",
  "it_model4_title": "Hợp đồng B2B & Ký kết NDA Chặt chẽ",
  "it_model4_desc": "Xuất hóa đơn VAT đầy đủ (MST: 0315397327), cam kết pháp lý bảo mật quyền sở hữu trí tuệ và không có bất kỳ tranh chấp lao động nào.",
  "it_roles_eyebrow": "_VỊ TRÍ KỸ THUẬT TRỌNG YẾU / ROLES & SKILLS/",
  "it_roles_title": "Đội Ngũ Kỹ Sư Senior Sẵn Sàng Nhận Việc Ngay",
  "it_roles_sub": "Đã trải qua quy trình đánh giá năng lực thuật toán, kiến trúc hệ thống và kỹ năng giao tiếp.",
  "it_roles_desc": "Chúng tôi tập trung cung cấp các vị trí kỹ thuật cấp cao, có khả năng độc lập giải quyết bài toán khó và hướng dẫn các thành viên khác trong team.",
  "it_role1_title": "Senior Backend Engineers",
  "it_role1_desc": "Chuyên sâu về kiến trúc phân tán, xử lý giao dịch cao tải, tối ưu truy vấn cơ sở dữ liệu và tích hợp API hệ thống ngân hàng (Rust, Go, Python, Node.js).",
  "it_role2_title": "Senior Frontend & Mobile Engineers",
  "it_role2_desc": "Xây dựng giao diện ứng dụng phức tạp, mượt mà chuẩn 60fps, tối ưu hóa tốc độ hiển thị và trải nghiệm người dùng đa thiết bị (SvelteKit, React, Flutter).",
  "it_role3_title": "DevOps & Cloud Infrastructure",
  "it_role3_desc": "Thiết lập hạ tầng điện toán đám mây tự động co giãn, xây dựng luồng CI/CD không gián đoạn và giám sát an toàn thông tin 24/7 (Docker, K8s, AWS, Terraform).",
  "it_role4_title": "QA / Automation Test Engineers",
  "it_role4_desc": "Viết kịch bản kiểm thử tự động toàn diện từ Unit test, API test đến E2E test, kiểm tra khả năng chịu tải và dò quét lỗ hổng (Playwright, Cypress, K6).",
  "it_steps_badge": "_QUY TRÌNH ONBOARDING THẦN TỐC/",
  "it_steps_title": "4 Bước Bổ Sung Kỹ Sư IT Vào Dự Án Trong 48 Giờ",
  "it_steps_desc": "Quy trình tinh gọn, bảo đảm khách hàng nắm toàn quyền kiểm tra năng lực và thử việc an toàn không rủi ro tài chính.",
  "it_step1_title": "Tiếp nhận Yêu cầu & Sàng lọc CV",
  "it_step1_desc": "CreditBird phân tích bài toán kỹ thuật của bạn và gửi danh sách hồ sơ ứng viên đạt tiêu chuẩn trong vòng 48 giờ.",
  "it_step2_title": "Phỏng vấn Trực tiếp 1:1",
  "it_step2_desc": "Khách hàng trực tiếp phỏng vấn kỹ thuật và kiểm tra năng lực thực chiến của kỹ sư để đảm bảo phù hợp văn hóa.",
  "it_step3_title": "Thử việc Đánh giá Thực tế 2 Tuần",
  "it_step3_desc": "Kỹ sư bắt đầu tham gia dự án với thời gian dùng thử 2 tuần. Nếu không đạt yêu cầu, đổi nhân sự hoàn toàn miễn phí.",
  "it_step4_title": "Ký Hợp đồng Dịch vụ & Onboarding",
  "it_step4_desc": "Ký hợp đồng dịch vụ chính thức giữa hai pháp nhân. CreditBird chịu trách nhiệm toàn bộ bảo hiểm, phúc lợi và hành chính.",
  "it_cta_eyebrow": "_BỔ SUNG KỸ SƯ NGAY HÔM NAY/",
  "it_cta_title": "Bổ Sung Ngay Kỹ Sư IT Trình Độ Cao Cho Dự Án Của Bạn",
  "it_cta_desc": "CreditBird cam kết cung cấp nhân sự đúng năng lực chuyên môn, thích ứng nhanh với văn hóa doanh nghiệp và sẵn sàng bắt tay vào việc ngay trong 48 giờ.",
  "it_cta_btn_primary": "Nhận Báo Giá & Hồ Sơ Kỹ Sư Trong 48H",

  // Subpage: Scent Marketing
  "scent_page_title": "Lemy Finest — Giải Pháp Scent Marketing & Tinh Dầu Thiên Nhiên | CreditBird",
  "scent_page_desc": "Lemy Finest (lemyfinest.com) — Máy khuếch tán tinh dầu kết nối HVAC và 100% tinh dầu thiên nhiên chuẩn kiểm định COA / GC-MS. Trực thuộc hệ sinh thái CreditBird.",
  "scent_hero_eyebrow": "_THƯƠNG HIỆU ĐỘC LẬP / LEMYFINEST.COM",
  "scent_hero_spec": "Scent Marketing • Máy Phun HVAC • Tinh Dầu COA / GC-MS",
  "scent_hero_title": "Giải Pháp Scent Marketing Toàn Diện Cho Doanh Nghiệp",
  "scent_hero_desc": "Thương hiệu tiếp thị mùi hương cao cấp thuộc CreditBird. Cung cấp giải pháp máy phun khuếch tán nano kết nối hệ thống HVAC và 100% tinh dầu thiên nhiên nguyên chất chuẩn quốc tế, kiến tạo không gian sang trọng và gia tăng doanh số.",
  "scent_hero_btn_primary": "Truy Cập Website LemyFinest.com",
  "scent_hero_btn_secondary": "Khảo Sát Không Gian & Thử Mùi Hương",
  "scent_metrics_eyebrow": "_CHỈ SỐ KỸ THUẬT / TECHNICAL TELEMETRY",
  "scent_metrics_title": "Tiêu chuẩn kiểm định quốc tế và công nghệ khuếch tán tiên tiến",
  "scent_metric1_label": "DIỆN TÍCH PHỦ SÓNG",
  "scent_metric1_val": "500 - 5.000 m²",
  "scent_metric1_sub": "Kết nối trực tiếp hệ thống ống gió điều hòa trung tâm HVAC",
  "scent_metric2_label": "CÔNG NGHỆ KHUẾCH TÁN",
  "scent_metric2_val": "< 0.1 µm",
  "scent_metric2_sub": "Hạt hương sương nano siêu mịn lơ lửng, tuyệt đối không ngưng tụ",
  "scent_metric3_label": "CHỨNG NHẬN CHẤT LƯỢNG",
  "scent_metric3_val": "100% COA",
  "scent_metric3_sub": "Phiếu kiểm định quốc tế COA & phân tích sắc ký khí GC-MS",
  "scent_metric4_label": "ĐIỀU KHIỂN THÔNG MINH",
  "scent_metric4_val": "WiFi & App",
  "scent_metric4_sub": "Lập trình hẹn giờ tự động và điều chỉnh mật độ hương theo khung giờ",
  "scent_solutions_eyebrow": "_GIẢI PHÁP CHỦ LỰC / CORE CAPABILITIES/",
  "scent_solutions_title": "Hệ Sinh Thái Thiết Bị Khuếch Tán & Mùi Hương Đẳng Cấp",
  "scent_solutions_sub": "Tùy biến linh hoạt từ phòng VIP riêng biệt đến toàn bộ tòa nhà cao ốc.",
  "scent_solutions_desc": "Chúng tôi kết hợp khoa học khứu giác hiện đại với các giải pháp phần cứng cơ điện lạnh tiên tiến để đưa hương thơm lan tỏa đồng đều tới từng góc không gian.",
  "scent_sol1_title": "Máy Khuếch Tán Công Nghiệp Kết Nối HVAC",
  "scent_sol1_desc": "Tích hợp trực tiếp vào hệ thống thông gió điều hòa trung tâm HVAC. Công nghệ sóng nano tách hạt tinh dầu siêu mịn dưới 0.1 micron, không ngưng tụ, phủ đều không gian 500 - 5.000m².",
  "scent_sol2_title": "Thiết Bị Khuếch Tán Thông Minh Phủ Sảnh & Showroom",
  "scent_sol2_desc": "Thiết kế sang trọng cho sảnh chờ, showroom, spa từ 100 - 500m². Cài đặt chính xác thời gian phun, cường độ hương theo từng khung giờ cao điểm qua App kết nối WiFi/Bluetooth.",
  "scent_sol3_title": "100% Tinh Dầu Thiên Nhiên Chuẩn COA & GC-MS",
  "scent_sol3_desc": "Nguyên liệu nhập khẩu chính ngạch, có đầy đủ phiếu kiểm nghiệm chất lượng COA (Certificate of Analysis) và phân tích sắc ký khí GC-MS, không cồn công nghiệp, tuyệt đối an toàn cho sức khỏe.",
  "scent_sol4_title": "Thiết Kế Mùi Hương Nhận Diện Thương Hiệu Độc Quyền",
  "scent_sol4_desc": "Đội ngũ chuyên gia mùi hương điều chế nốt hương độc bản (Bespoke Signature Scent), tạo dấu ấn cảm xúc khó quên giúp gia tăng thời gian lưu lại và hành vi mua sắm của khách hàng.",
  "scent_sol5_title": "Dịch Vụ Cung Cấp Định Kỳ & Bảo Trì Tận Nơi",
  "scent_sol5_desc": "Gói giải pháp trọn gói hàng tháng: nhân viên kỹ thuật đến nạp tinh dầu định kỳ, vệ sinh kim phun, thay lọc định kỳ, bảo đảm không gian của bạn luôn thơm mát liên tục.",
  "scent_sol6_title": "Bảo Hành 12 - 24 Tháng & Đổi Mới Linh Kiện",
  "scent_sol6_desc": "Cam kết chính sách bảo hành chính hãng từ 12 đến 24 tháng cho thiết bị, đổi mới máy nếu phát sinh lỗi kỹ thuật từ nhà sản xuất trong vòng 30 ngày đầu tiên.",
  "scent_sectors_eyebrow": "_LĨNH VỰC ỨNG DỤNG / SECTORS & APPLICATIONS/",
  "scent_sectors_title": "Nâng Tầm Không Gian Cảm Xúc Trong Mọi Ngành Nghề",
  "scent_sectors_sub": "Khơi gợi giác quan mạnh mẽ nhất của con người để tạo dựng lòng trung thành thương hiệu.",
  "scent_sectors_desc": "Nghiên cứu cho thấy khách hàng sẵn sàng chi trả nhiều hơn và lưu lại lâu hơn 40% trong không gian có mùi hương phù hợp.",
  "scent_sec1_title": "Khách Sạn & Resort Nghỉ Dưỡng",
  "scent_sec1_desc": "Đón tiếp du khách bằng hương thơm sang trọng, thư thái ngay từ khi bước vào tiền sảnh, ghi dấu ấn trải nghiệm đẳng cấp 5 sao.",
  "scent_sec2_title": "Showroom Ô Tô & Bất Động Sản",
  "scent_sec2_desc": "Khẳng định đẳng cấp không gian giao dịch, khơi gợi cảm xúc tin cậy và thúc đẩy quyết định xuống tiền mua tài sản giá trị cao.",
  "scent_sec3_title": "Chuỗi Bán Lẻ & Thời Trang",
  "scent_sec3_desc": "Định hình phong cách thương hiệu thời thượng, kéo dài thời gian mua sắm và gia tăng tỷ lệ quay lại của khách hàng trung thành.",
  "scent_sec4_title": "Bệnh Viện Thẩm Mỹ, Nha Khoa & Spa",
  "scent_sec4_desc": "Khử mùi kháng khuẩn tự nhiên, xua tan cảm giác lo âu căng thẳng và tạo môi trường nghỉ dưỡng thư thái tuyệt đối.",
  "scent_hvac_eyebrow": "_CÔNG NGHỆ HVAC NANO / DIFFUSION TECHNOLOGY",
  "scent_hvac_title": "Giải Pháp Khuếch Tán Hương Thơm Qua Ống Gió Điều Hòa",
  "scent_hvac_desc": "Công nghệ ép áp suất lạnh tạo ra các hạt hương kích thước dưới 0.1 micron, nhẹ hơn không khí và hoàn toàn không làm ẩm ướt hệ thống ống gió điều hòa.",
  "scent_hvac_link": "Khám phá bộ sưu tập tinh dầu tại LemyFinest.com",
  "scent_bullet1_title": "Khuếch tán Nano siêu mịn",
  "scent_bullet1_text": "Hạt tinh dầu phân tách dưới 0.1 micron, bay theo luồng gió điều hòa bao phủ toàn bộ diện tích sàn mà không để lại bất kỳ giọt dầu đọng nào.",
  "scent_bullet2_title": "Kiểm soát thông minh qua IoT",
  "scent_bullet2_text": "Lập lịch tự động bật/tắt theo ca làm việc, điều chỉnh nồng độ phun theo từng mét khối không khí thực tế.",
  "scent_bullet3_title": "Tiết kiệm chi phí vận hành",
  "scent_bullet3_text": "Mức tiêu hao tinh dầu cực kỳ tối ưu, giảm hơn 40% chi phí so với việc đặt nhiều máy phun nhỏ phân tán.",
  "scent_cta_eyebrow": "_TRẢI NGHIỆM MÙI HƯƠNG MIỄN PHÍ/",
  "scent_cta_title": "Khám Phá Sức Mạnh Tiếp Thị Mùi Hương Cho Doanh Nghiệp Bạn",
  "scent_cta_desc": "Chuyên viên Lemy Finest sẽ mang mẫu thử tinh dầu trực tiếp và thiết bị demo đến tận cơ sở kinh doanh của bạn để bạn trải nghiệm thực tế trước khi quyết định.",
  "scent_cta_btn_primary": "Đăng Ký Mang Mẫu Thử Mùi Hương Tận Nơi",
  "scent_cta_btn_secondary": "Khám Phá Website LemyFinest.com",

  // Subpage: RustSale CRM
  "rs_page_title": "RustSale CRM & Outreach Pro — Growth Operating System All-in-One | CreditBird",
  "rs_page_desc": "Phần mềm Desktop CRM Chat Omnichannel (Zalo, WhatsApp, Facebook) viết bằng Rust Native. Xử lý microsecond, bảo mật Local-First, cẩm nang toàn tập trên Notion.",
  "rs_hero_eyebrow": "_PHẦN MỀM ĐỘC QUYỀN / RUST NATIVE",
  "rs_hero_spec": "Tauri v2 • Microsecond Latency • Local-First",
  "rs_hero_title": "RustSale CRM & Outreach Pro",
  "rs_hero_desc": "Hệ điều hành tăng trưởng doanh số All-in-One. Hợp nhất Zalo, WhatsApp, Facebook Messenger trên một giao diện Desktop duy nhất. Viết bằng ngôn ngữ Rust thuần túy cho tốc độ phản hồi tính bằng microsecond và độ ổn định tuyệt đối.",
  "rs_hero_btn_primary": "Xem Cẩm nang Toàn tập (Notion)",
  "rs_hero_btn_secondary": "Đăng ký Demo Trải nghiệm",
  "rs_metrics_eyebrow": "_HIỆU NĂNG VẬN HÀNH / SYSTEM TELEMETRY",
  "rs_metrics_title": "Khác biệt vượt trội từ nền tảng công nghệ Rust Native",
  "rs_metric1_label": "TỐC ĐỘ XỬ LÝ",
  "rs_metric1_val": "< 1 ms",
  "rs_metric1_sub": "Độ trễ microsecond do Rust native biên dịch trực tiếp",
  "rs_metric2_label": "TIÊU THỤ RAM",
  "rs_metric2_val": "< 45 MB",
  "rs_metric2_sub": "Tiết kiệm 90% RAM so với ứng dụng nền Electron",
  "rs_metric3_label": "BẢO MẬT DỮ LIỆU",
  "rs_metric3_val": "Local-First",
  "rs_metric3_sub": "Mã hóa SQLite & Keyring cấp hệ điều hành máy tính",
  "rs_metric4_label": "PHÂN HỆ TÍCH HỢP",
  "rs_metric4_val": "12 Phân hệ",
  "rs_metric4_sub": "Từ trích xuất Google Maps đến Hộp thư hội tụ đa kênh",
  "rs_modules_eyebrow": "_12 PHÂN HỆ CHUYÊN SÂU KHÉP KÍN/",
  "rs_modules_title": "Bộ Công Cụ Tăng Trưởng Toàn Diện Cho Sales & Marketing B2B",
  "rs_modules_sub": "Từ quét dữ liệu Google Maps đến quản lý hợp đồng và chăm sóc khách hàng trọn đời.",
  "rs_modules_desc": "RustSale CRM & Outreach Pro được cấu trúc module hóa độc lập, chạy trực tiếp trên nền hệ điều hành (Windows/macOS/Linux) với khả năng mở rộng không giới hạn.",
  "rs_mod1_title": "Trung tâm Chỉ huy & Phân tích Pipeline",
  "rs_mod1_desc": "Giám sát chỉ số outreach, số lead mới phát sinh, tỷ lệ phản hồi tin nhắn và giá trị phễu chuyển đổi thời gian thực.",
  "rs_mod2_title": "Khai thác Khách hàng Địa phương",
  "rs_mod2_desc": "Quét tự động thông tin doanh nghiệp theo khu vực địa lý, trích xuất chính xác số điện thoại, website, địa chỉ kinh doanh.",
  "rs_mod3_title": "Động cơ Quản lý & Lọc trùng Khách hàng",
  "rs_mod3_desc": "Phân nhóm khách hàng tiềm năng, khử trùng lặp dữ liệu thông minh, tự động chuẩn hóa định dạng số điện thoại và email.",
  "rs_mod4_title": "Định danh Đa tầng & Phân khúc Mục tiêu",
  "rs_mod4_desc": "Hệ thống nhãn dán tùy biến, phân loại khách hàng theo nhóm ngành nghề, quy mô doanh nghiệp và giai đoạn tiếp cận.",
  "rs_mod5_title": "Hộp Thư Hội Tụ & AI Smart Reply",
  "rs_mod5_desc": "Hợp nhất tin nhắn Zalo, WhatsApp, Facebook Messenger về 1 cửa sổ. Tích hợp AI Agent phân tích ý định và gợi ý câu trả lời chốt sales tức thì.",
  "rs_mod6_title": "Quản trị Tập trung Đa Fanpage",
  "rs_mod6_desc": "Kết nối và điều hành nhiều Fanpage Facebook cùng lúc, tự động hóa kịch bản trả lời inbox, bình luận bài viết theo từ khóa.",
  "rs_mod7_title": "AI Agent Tiếp Cận & Chăm Sóc Đa Kênh",
  "rs_mod7_desc": "Tự động gửi kết bạn Zalo, phân loại cảm xúc khách hàng và kích hoạt chuỗi nuôi dưỡng thông minh bằng AI Agent chuyên trách.",
  "rs_mod8_title": "Chiến dịch Tin nhắn WhatsApp B2B",
  "rs_mod8_desc": "Gửi thông báo chăm sóc đơn hàng, cập nhật hợp đồng và chăm sóc khách hàng quốc tế với tỷ lệ mở tin nhắn trên 95%.",
  "rs_mod9_title": "Chuỗi Email Nuôi dưỡng Khách hàng B2B",
  "rs_mod9_desc": "Thiết lập chiến dịch email marketing tự động hóa theo kịch bản, theo dõi tỷ lệ mở email, tỷ lệ click link chi tiết.",
  "rs_mod10_title": "Bảng Điều hướng Bán hàng Kéo thả",
  "rs_mod10_desc": "Quản trị quy trình đàm phán trực quan từ Tiềm năng -> Báo giá -> Thương thảo -> Ký HĐ với thao tác kéo thả mượt mà.",
  "rs_mod11_title": "Quản trị Khách hàng Chốt Thành công",
  "rs_mod11_desc": "Lưu trữ hồ sơ khách hàng đã ký hợp đồng, lịch sử giao dịch và kế hoạch chăm sóc gia hạn dịch vụ định kỳ trọn đời.",
  "rs_mod12_title": "Kho Mật mã Mã hóa Cấp Phần cứng",
  "rs_mod12_desc": "Toàn bộ API Keys và cơ sở dữ liệu được mã hóa lưu trữ Local-First trên thiết bị người dùng, bảo vệ quyền riêng tư tuyệt đối.",
  "rs_split_eyebrow": "_HỘP THƯ HỘI TỤ / OMNICHANNEL INBOX",
  "rs_split_title": "Tất Cả Tin Nhắn Khách Hàng Trên 1 Màn Hình Duy Nhất",
  "rs_split_desc": "Không còn tình trạng nhân viên kinh doanh phải chuyển đổi qua lại giữa hàng loạt ứng dụng Zalo, trình duyệt web WhatsApp và Fanpage Facebook gây chậm trễ và sót khách hàng.",
  "rs_split_link": "Đọc hướng dẫn thiết lập Omnichannel trên Notion",
  "rs_bullet1_title": "Đồng bộ đa tài khoản Zalo",
  "rs_bullet1_text": "Quản lý song song Zalo cá nhân và Zalo Doanh nghiệp (OA) trong một giao diện duy nhất.",
  "rs_bullet2_title": "AI Agent Chốt đơn & Trợ lý thông minh",
  "rs_bullet2_text": "Phân tích hội thoại thời gian thực, tự động gợi ý câu trả lời và kịch bản chốt đơn cá nhân hóa.",
  "rs_bullet3_title": "WhatsApp Cloud & Web Hub",
  "rs_bullet3_text": "Gửi thông báo tự động, chăm sóc khách hàng xuất nhập khẩu và khách quốc tế mượt mà.",
  "rs_bullet4_title": "Quản trị Facebook Fanpage",
  "rs_bullet4_text": "Gom toàn bộ tin nhắn inbox và bình luận đa page về trung tâm chỉ huy.",
  "rs_bullet5_title": "Kịch bản phản hồi nhanh (Quick Replies)",
  "rs_bullet5_text": "Tạo sẵn mẫu tin nhắn chuyên nghiệp theo từng phân khúc ngành nghề cho nhân viên tư vấn.",
  "rs_doc_eyebrow": "_HƯỚNG DẪN KỸ THUẬT CHÍNH THỨC/",
  "rs_doc_title": "Cẩm Nang Sử Dụng Toàn Tập Trên Notion",
  "rs_doc_desc": "Toàn bộ quy trình cài đặt trên Linux/Windows/macOS, thiết lập khóa bảo mật Keyring, cấu hình Zalo Outreach và kịch bản tin nhắn bán hàng đã được số hóa chi tiết và cập nhật liên tục.",
  "rs_doc_btn_notion": "Mở Notion Cẩm Nang",
  "rs_doc_btn_github": "GitHub CreditBird",
  "rs_cta_eyebrow": "_SẴN SÀNG TRIỂN KHAI/",
  "rs_cta_title": "Trải Nghiệm Sức Mạnh Tốc Độ Microsecond Của RustSale CRM",
  "rs_cta_desc": "Được phát triển và bảo chứng kỹ thuật bởi CÔNG TY TNHH CÔNG NGHỆ CREDITBIRD (MST: 0315397327). Đội ngũ kỹ sư sẵn sàng hỗ trợ cài đặt và chuyển giao quy trình cho doanh nghiệp của bạn.",
  "rs_cta_btn_primary": "Đăng Ký Buổi Tư Vấn & Demo 1:1",

  // Legal Common
  "terms_hero_eyebrow": "_PHÁP LÝ & ĐIỀU KHOẢN/",
  "terms_spec": "Hiệu lực: Tháng 01/2026",
  "terms_hero_title": "Điều khoản Dịch vụ",
  "terms_hero_desc": "Quy định và điều khoản sử dụng các giải pháp, dịch vụ được cung cấp bởi CÔNG TY TNHH CÔNG NGHỆ CREDITBIRD (Mã số thuế: 0315397327).",
  "privacy_hero_eyebrow": "_BẢO MẬT DỮ LIỆU & QUYỀN RIÊNG TƯ/",
  "privacy_spec": "Chuẩn ISO 27001 & Nghị định 13/2023/NĐ-CP",
  "privacy_hero_title": "Chính sách Bảo mật Dữ liệu",
  "privacy_hero_desc": "Cam kết bảo vệ dữ liệu cá nhân, thông tin doanh nghiệp và bí mật công nghệ tuân thủ Nghị định 13/2023/NĐ-CP của CÔNG TY TNHH CÔNG NGHỆ CREDITBIRD (MST: 0315397327).",
  "warranty_hero_eyebrow": "_BẢO HÀNH & SLA DỊCH VỤ/",
  "warranty_spec": "Cam kết chuẩn mực 2026",
  "warranty_hero_title": "Chính sách Bảo hành & SLA Dịch vụ",
  "warranty_hero_desc": "Cam kết chất lượng thiết bị máy phun tinh dầu 12 - 24 tháng, tinh dầu thiên nhiên 100% nguyên chất có kiểm định COA và cam kết mức độ dịch vụ (SLA) phần mềm, ERP đạt 99.9% uptime của CÔNG TY TNHH CÔNG NGHỆ CREDITBIRD (MST: 0315397327).",
  "security_hero_eyebrow": "_TIÊU CHUẨN AN TOÀN THÔNG TIN/",
  "security_spec": "Chuẩn mực OWASP Top 10 & DevSecOps",
  "security_hero_title": "Tiêu Chuẩn An Toàn & An Ninh Thông Tin",
  "security_hero_desc": "Hệ thống chính sách, quy trình kỹ thuật và tiêu chuẩn an toàn thông tin áp dụng cho toàn bộ dự án phần mềm, ERP và thiết bị IoT của CÔNG TY TNHH CÔNG NGHỆ CREDITBIRD (MST: 0315397327).",
  "legal_toc_title": "MỤC LỤC TÀI LIỆU",
  "legal_btn_partner": "Đăng Ký Hợp Tác Doanh Nghiệp",
  "legal_btn_consult": "Đăng Ký Tư Vấn Dịch Vụ"
};

// Define new English keys
const enNew: Record<string, string> = {
  // Common / Navbar / General
  "navbar_announcement_company": "CREDITBIRD TECHNOLOGY CO., LTD • Custom Software, Kelvot ERP & Lemy Finest Scent",
  "navbar_tagline": "Creating Value For You",
  "navbar_select_language": "Language / Ngôn ngữ",
  "navbar_call_hotline": "Hotline: (+84) 932 640 968",

  // Hero Section
  "hero_option_label": "OPTION",

  // Core Domains
  "domain_software_code": "_DOMAIN 01 / BESPOKE SOFTWARE",
  "domain_erp_code": "_DOMAIN 02 / KELVOT ERP ECOSYSTEM",
  "domain_scent_code": "_DOMAIN 03 / SCENT MARKETING",
  "domain_erp_feat_1": "Multi-BOM & Manufacturing Orders (MO)",
  "domain_erp_feat_2": "Smart WMS Warehouse & Barcode/QR Tracking",
  "domain_erp_feat_3": "General Ledger & VAS (Circular 200) / IFRS Accounting",
  "domain_erp_feat_4": "Real-time Cost and Inventory Audit",
  "domain_erp_website": "Kelvot.com Website",
  "domain_scent_feat_1": "Desktop aroma diffusers for modern office spaces",
  "domain_scent_feat_2": "Industrial HVAC aroma diffusion systems",
  "domain_scent_feat_3": "Pure certified essential oils with COA / GC-MS profiles",
  "domain_scent_feat_4": "Flexible monthly refill & maintenance plans",
  "domain_scent_website": "LemyFinest.com Website",

  // Featured Showcase: Tab 1 (RustSale CRM)
  "showcase_tab1_badge": "UI MOCKUP / RUST NATIVE CRM",
  "showcase_tab1_title": "RustSale CRM — Omnichannel Hub for Zalo, WhatsApp, Messenger",
  "showcase_tab1_desc": "Engineered in native Rust for peak performance, RustSale CRM unifies fragmented messaging channels and prevents lead leakage. Data is encrypted and stored locally on your company devices.",
  "showcase_tab1_feat1": "Manage multiple personal Zalo accounts & Zalo OA simultaneously on one screen",
  "showcase_tab1_feat2": "Integrate B2B WhatsApp chats and Facebook Fanpage Messenger",
  "showcase_tab1_feat3": "Lead tag filtering, transaction history logs, and consultant assignment",
  "showcase_tab1_btn_explore": "Explore RustSale CRM",
  "showcase_tab1_btn_custom": "Custom Software Services",
  "showcase_tab1_mockup_title": "RustSale Omnichannel Hub (Mockup Preview)",
  "showcase_tab1_mockup_connected": "CONNECTED 4 CHANNELS",
  "showcase_tab1_mockup_col1_header": "UNIFIED CONVERSATIONS",
  "showcase_tab1_mockup_chat1_name": "[Zalo] An Phat Steel Co.",
  "showcase_tab1_mockup_chat1_preview": "Please quote our steel pipe order...",
  "showcase_tab1_mockup_chat2_name": "[WhatsApp] FDI Logistics",
  "showcase_tab1_mockup_chat2_preview": "Contract terms approved.",
  "showcase_tab1_mockup_chat3_name": "[FB Page] Pharmacy Chain",
  "showcase_tab1_mockup_chat3_preview": "Diffuser inquiry for main lobby...",
  "showcase_tab1_mockup_col2_header": "AN PHAT STEEL CO. (ZALO B2B)",
  "showcase_tab1_mockup_badge_hot": "HOT LEAD",
  "showcase_tab1_mockup_client_label": "Client:",
  "showcase_tab1_mockup_client_msg": "We need bespoke warehouse software integrated with barcode scanning and accounting, please advise.",
  "showcase_tab1_mockup_cb_msg": "CreditBird offers Kelvot ERP specializing in BOM consumption and barcode WMS, let me send you the specs via Zalo.",
  "showcase_tab1_mockup_local": "Local-First Data Processing",
  "showcase_tab1_mockup_note": "* Feature mockup preview; actual deployment configured according to business needs.",

  // Featured Showcase: Tab 2 (Kelvot ERP)
  "showcase_tab2_badge": "UI MOCKUP / KELVOT ERP",
  "showcase_tab2_title": "Kelvot ERP — Engineered for Manufacturing, Warehousing & VAS Accounting",
  "showcase_tab2_desc": "Engineered strictly adhering to Vietnamese Accounting Standards (Circular 200/133) and solving core manufacturing bottlenecks: BOM scrap control, barcode WMS, and stage-by-stage cost computation.",
  "showcase_tab2_card1_title": "MULTI-LEVEL BOM MATRIX",
  "showcase_tab2_card1_desc": "Automated material breakdown and consumption limits per manufacturing order.",
  "showcase_tab2_card2_title": "WMS SMART WAREHOUSING",
  "showcase_tab2_card2_desc": "Barcode scanning for bin-location tracking, batch traceability, and expiration dates.",
  "showcase_tab2_card3_title": "MANAGERIAL ACCOUNTING",
  "showcase_tab2_card3_desc": "Automated general ledger journals, revenue, expense, and tax compliance reports.",
  "showcase_tab2_card4_title": "OPEN API INTEGRATION",
  "showcase_tab2_card4_desc": "Seamless integration with e-invoicing, core banking, and e-commerce platforms.",
  "showcase_tab2_btn_details": "Kelvot ERP Solution Details",
  "showcase_tab2_btn_website": "Kelvot.com Website",
  "showcase_tab2_table_title": "[MOCKUP PREVIEW] MANUFACTURING ORDER: MO-2026-089",
  "showcase_tab2_table_status": "IN PROGRESS",
  "showcase_tab2_th_code": "ITEM CODE",
  "showcase_tab2_th_name": "MATERIAL NAME",
  "showcase_tab2_th_norm": "PLANNED BOM",
  "showcase_tab2_th_actual": "ACTUAL ISSUED",
  "showcase_tab2_th_status": "STATUS",
  "showcase_tab2_row1_name": "Cold Rolled Steel Sheet 1.2mm",
  "showcase_tab2_row2_name": "Technical Copper Wire dia 0.8",
  "showcase_tab2_row3_name": "Stainless Steel Bolt & Nut M6x20",
  "showcase_tab2_row_unit_kg": "kg",
  "showcase_tab2_row_unit_pcs": "pcs",
  "showcase_tab2_status_complete": "100% COMPLETE",
  "showcase_tab2_journal_label": "Automated Accounting Entry:",
  "showcase_tab2_journal_val": "Dr Account 154 / Cr Account 152 (VAS/IFRS)",
  "showcase_tab2_table_note": "* Simulated BOM calculation; actual configuration customized per factory workflow.",

  // Featured Showcase: Tab 3 (Scent & Lemy Finest)
  "showcase_tab3_badge": "SCENT HARDWARE & PURE OILS / LEMYFINEST.COM",
  "showcase_tab3_title": "Lemy Finest Essential Oils & Smart Aroma Diffusion Hardware",
  "showcase_tab3_desc": "CreditBird delivers two flagship offerings: Smart cold-air aroma diffusion systems (desktop and HVAC connected) alongside pure essential oils with verified COA reports and GC-MS chromatography profiles.",
  "showcase_tab3_policy_title": "Supply & Service Model:",
  "showcase_tab3_policy_item1_label": "Equipment Purchase:",
  "showcase_tab3_policy_item1_val": "Full warranty coverage backed by B2B service contracts.",
  "showcase_tab3_policy_item2_label": "Leasing & Scheduled Refills:",
  "showcase_tab3_policy_item2_val": "Onsite cubic volume survey, installation, routine maintenance, and scheduled oil refills.",
  "showcase_tab3_policy_item3_label": "Wholesale & Commercial Supply:",
  "showcase_tab3_policy_item3_val": "500ml and 1,000ml canisters or 50ml and 100ml bottles.",
  "showcase_tab3_btn_consult": "Request Scent & Hardware Consultation",
  "showcase_tab3_btn_details": "Scent Solution Details",
  "showcase_tab3_card1_badge": "DIFFUSION HARDWARE",
  "showcase_tab3_card1_tag": "2 PRODUCT LINES",
  "showcase_tab3_card1_title": "Nano-Mist Cold-Air Diffusers",
  "showcase_tab3_card1_item1_label": "1. Desktop Aroma Diffusers:",
  "showcase_tab3_card1_item1_desc": "Ideal for executive offices, meeting rooms, spas, and residential spaces. Coverage: 30–80 m².",
  "showcase_tab3_card1_item2_label": "2. Central HVAC Industrial Systems:",
  "showcase_tab3_card1_item2_desc": "Engineered for hotel grand lobbies, automobile showrooms, and corporate towers. Coverage: 500–5,000 m².",
  "showcase_tab3_card1_note": "* Technical specifications and coverage metrics verified per device compliance dossier.",
  "showcase_tab3_card1_link": "View Diffuser Specifications",
  "showcase_tab3_card2_badge": "COA TESTED OILS",
  "showcase_tab3_card2_tag": "VERIFIED GC-MS",
  "showcase_tab3_card2_title": "Certified Pure Essential Oils",
  "showcase_tab3_card2_item1_label": "Popular Signatures:",
  "showcase_tab3_card2_item1_desc": "Sweet Orange, Lemongrass, White Tea, Oud Wood, French Lavender.",
  "showcase_tab3_card2_item2_label": "Certification & Safety:",
  "showcase_tab3_card2_item2_desc": "Each oil batch comes with a verified Certificate of Analysis (COA) and GC-MS purity profile.",
  "showcase_tab3_card2_item3_label": "Packaging Formats:",
  "showcase_tab3_card2_item3_desc": "50ml, 100ml bottles and 500ml, 1,000ml commercial containers.",
  "showcase_tab3_card2_note": "* Laboratory test certificates and COA dossiers provided upon consultation and delivery.",
  "showcase_tab3_card2_link": "Explore Scent Library",

  // How We Work Section
  "workflow_tech_tag": "TECHNICAL WORKFLOW",
  "workflow_tech_title": "1. Bespoke Software & Kelvot ERP",
  "workflow_tech_step1_title": "Discovery & Architecture Blueprint",
  "workflow_tech_step1_desc": "In-depth analysis of existing workflows, architectural consulting, functional specification authoring, and B2B contract execution with NDA.",
  "workflow_tech_step2_title": "Iterative Phased Development",
  "workflow_tech_step2_desc": "Structured milestone sprints, regular automated testing, and ongoing staging reviews for hands-on client feedback.",
  "workflow_tech_step3_title": "UAT Acceptance & User Training",
  "workflow_tech_step3_desc": "Rigorous end-to-end acceptance testing against agreed specs, staff training, and data migration execution.",
  "workflow_tech_step4_title": "Source Handover & SLA Support",
  "workflow_tech_step4_desc": "Complete handover of Git repositories, architectural documentation, and 12-24 months proactive warranty.",
  "workflow_scent_tag": "SCENT MARKETING WORKFLOW",
  "workflow_scent_title": "2. Scent Marketing & Diffusion Services",
  "workflow_scent_step1_title": "Volume & Airflow Survey",
  "workflow_scent_step1_desc": "Precise calculation of floor area (m²) and ceiling height (m) alongside HVAC airflow analysis.",
  "workflow_scent_step2_title": "Scent Sampling & Hardware Sizing",
  "workflow_scent_step2_desc": "Onsite olfactory sampling of COA-certified oils and selection of optimal desktop or HVAC diffusion models.",
  "workflow_scent_step3_title": "Installation & IoT Scheduling",
  "workflow_scent_step3_desc": "Clean professional installation, automated timer configuration, and nano-diffusion intensity adjustment.",
  "workflow_scent_step4_title": "Scheduled Maintenance & Refills",
  "workflow_scent_step4_desc": "Routine nozzle maintenance, hardware diagnostics, and scheduled oil refills per B2B SLA contract.",
  "workflow_cta_quote": "Request Workflow Consultation",

  // Real Use Cases Section
  "usecases_label_problem": "Common Challenge:",
  "usecases_label_solution": "CreditBird Solution:",
  "usecase_1_title": "Manufacturing & Processing Plants",
  "usecase_1_problem": "Difficulty in tracking raw material consumption limits and inventory discrepancies between physical stock and accounting records.",
  "usecase_1_solution": "Deploy Kelvot ERP for multi-level BOM tracking, barcode warehouse operations, and automated VAS cost accounting.",
  "usecase_1_link": "Explore Manufacturing ERP",
  "usecase_2_title": "Commercial & Retail Enterprises",
  "usecase_2_problem": "Customer conversations fragmented across multiple personal Zalo accounts and Facebook pages lead to lost leads.",
  "usecase_2_solution": "Implement RustSale CRM to consolidate Zalo, WhatsApp, and Messenger into a unified desktop dashboard with lead tags and history.",
  "usecase_2_link": "Explore RustSale CRM",
  "usecase_3_title": "Hotels, Resorts, Spas & Showrooms",
  "usecase_3_problem": "Lobby and service areas lack distinctive sensory identity or suffer from air conditioner odor.",
  "usecase_3_solution": "Install Lemy Finest nano diffusers integrated with central HVAC and pure COA-certified essential oils.",
  "usecase_3_link": "View HVAC Scent Solutions",
  "usecase_4_title": "Enterprises Requiring Bespoke Internal Software",
  "usecase_4_problem": "Commercial off-the-shelf software fails to match specialized proprietary workflows.",
  "usecase_4_solution": "CreditBird engineers custom web/mobile platforms matching exact logic, hands over 100% source code, and augments senior IT engineers.",
  "usecase_4_link": "Bespoke Software Development",

  // Footer
  "footer_custom_services": "BESPOKE SERVICES",
  "footer_custom_web_app": "Bespoke Web & Mobile Applications",
  "footer_custom_microservices": "Microservices Architecture, 100% Code Handover",
  "footer_it_senior": "Senior IT Staff Augmentation (Onsite/Remote)",
  "footer_github_repo": "Open Source Repositories (GitHub)",
  "footer_facebook_page": "Official Fanpage (Facebook)",
  "footer_rustsale_products": "RUSTSALE CRM PRODUCT",
  "footer_rustsale_inbox": "Unified Zalo, WhatsApp, Messenger Inbox",
  "footer_rustsale_keyring": "Local Keyring Security Storage",
  "footer_rustsale_notion": "Comprehensive User Guide (Notion)",
  "footer_erp_modules": "ERP MODULES",
  "footer_erp_bom": "Multi-Level Manufacturing BOM",
  "footer_erp_wms": "Barcode/QR Smart WMS Warehousing",
  "footer_erp_vas": "VAS (Circular 200) & IFRS Accounting",
  "footer_erp_cashflow": "Automated Cashflow & Cost Calculation",
  "footer_erp_brand": "INDEPENDENT BRAND",
  "footer_erp_portal": "Official Kelvot.com Portal",
  "footer_erp_license": "Request Survey & Implementation License",
  "footer_scent_brand": "LEMY FINEST ESSENTIAL OILS",
  "footer_scent_diffusers": "NANO AROMA DIFFUSERS",
  "footer_scent_desktop": "Desktop Diffusers for Offices",
  "footer_scent_hvac": "Industrial HVAC Systems (500 - 5,000m²)",
  "footer_scent_leasing": "Diffuser Leasing & Scheduled Refills",
  "footer_scent_warranty": "Hardware Warranty Under Service SLA",
  "footer_scent_oils": "COA CERTIFIED NATURAL OILS",
  "footer_scent_coa_desc": "Pure Natural Oils with COA / GC-MS",
  "footer_scent_scent_chart": "Scent Profiles for Hotels, Spas & Showrooms",
  "footer_scent_website": "Official LemyFinest.com Website",
  "footer_hotline_title": "HOTLINE & B2B",

  // Demo Modal
  "modal_err_required": "Please fill in your full name, phone number, and corporate email.",
  "modal_err_generic": "An error occurred while submitting. Please call our hotline (+84) 932 640 968.",
  "modal_err_network": "Unable to connect to server. Please call us directly or message via Zalo.",

  // Subpage: Software
  "sw_page_title": "Custom Software Development on Demand — CreditBird (Tax ID: 0315397327)",
  "sw_page_desc": "Enterprise bespoke software development, microservices architecture (Rust, Go, Python, SvelteKit). 100% full source code handover, 99.9% SLA commitment.",
  "sw_hero_eyebrow": "_CORE BUSINESS ACTIVITIES / TAX ID: 0315397327",
  "sw_hero_spec": "Microservices • 100% Full Source Code • Zero Vendor Lock-in",
  "sw_hero_title": "Bespoke Enterprise Software Engineered on Demand",
  "sw_hero_desc": "Delivering architectural design and bespoke software development tailored to unique operational workflows. 100% clean source code ownership handover, comprehensive warranty, and sustainable digital transformation partnership.",
  "sw_hero_btn_primary": "Request Software Architecture Consultation",
  "sw_hero_btn_secondary": "Explore 6-Step Roadmap",
  "sw_metrics_eyebrow": "_ENGINEERING STANDARDS / ARCHITECTURE",
  "sw_metrics_title": "Bank-grade stability and clean code assurance",
  "sw_metric1_label": "SOURCE CODE HANDOVER",
  "sw_metric1_val": "100% Full Code",
  "sw_metric1_sub": "Full Git repository, API documentation, and architecture diagrams",
  "sw_metric2_label": "CONCURRENCY CAPACITY",
  "sw_metric2_val": "100k+ CCU",
  "sw_metric2_sub": "High-concurrency architecture built with Rust, Go, and Microservices",
  "sw_metric3_label": "OPERATIONAL SLA",
  "sw_metric3_val": "SLA 99.9%",
  "sw_metric3_sub": "Emergency incident response guaranteed under 15 minutes",
  "sw_metric4_label": "TECHNICAL WARRANTY",
  "sw_metric4_val": "12 - 24 Months",
  "sw_metric4_sub": "Complimentary security patches and dedicated knowledge transfer",
  "sw_pillar_eyebrow": "_6 TECHNICAL PILLARS / ARCHITECTURE/",
  "sw_pillar_title": "Modern Engineering Foundations for Scaling Enterprises",
  "sw_pillar_sub": "Eliminate vendor lock-in concerns with 100% source code ownership handover.",
  "sw_pillar_desc": "We apply world-class software engineering standards to ensure high concurrent workloads run with rock-solid stability.",
  "sw_pillar1_title": "Microservices Architecture & AI-Ready",
  "sw_pillar1_desc": "High-performance backends with Rust, Go, and Python, optimized for zero memory leaks and integrated with AI inference pipelines.",
  "sw_pillar2_title": "100% Clean Source Code & AI Weights Ownership",
  "sw_pillar2_desc": "Complete ownership of Git repos, database schemas, API specs, and proprietary trained AI model weights. Zero vendor lock-in.",
  "sw_pillar3_title": "Bank-Grade Security & Private AI",
  "sw_pillar3_desc": "End-to-end data encryption at rest and in transit. Private on-premise LLMs ensuring corporate data sovereignty.",
  "sw_pillar4_title": "Fullstack Web, Mobile & AI Agents",
  "sw_pillar4_desc": "SvelteKit, React, and Flutter providing responsive 60fps experiences with embedded conversational AI agents.",
  "sw_pillar5_title": "Core Banking Integration & Agentic Workflows",
  "sw_pillar5_desc": "Seamless connectivity with bank hubs, VietQR, automated ledger reconciliation, and autonomous agentic workflows.",
  "sw_pillar6_title": "99.9% SLA & Continuous Technology Updates",
  "sw_pillar6_desc": "12-24 months proactive warranty, 24/7 incident response under 15 minutes, and continuous framework modernization.",
  "sw_tech_eyebrow": "_TECH STACK MATRIX / SPECIALIZED TECH/",
  "sw_tech_title": "Optimized Technology Selection for Every Challenge",
  "sw_tech_sub": "Focused on modern typed languages, memory safety, and sub-millisecond response times.",
  "sw_tech_desc": "Each project is engineered with the most suitable technology stack to maximize throughput and minimize cloud infrastructure costs.",
  "sw_tech1_title": "Ultra-Fast Backend Systems",
  "sw_tech1_desc": "Rust, Golang, Python, and Node.js microservices engineered for high concurrency and zero memory bloat.",
  "sw_tech2_title": "Enterprise AI & Autonomous Agents",
  "sw_tech2_desc": "Integration with OpenAI/Claude/Llama, private on-premise LLMs, enterprise RAG knowledge bases, and agentic workflows.",
  "sw_tech3_title": "Frontend Web Applications",
  "sw_tech3_desc": "SvelteKit, React, Tailwind CSS, and TypeScript leveraging SSR/SSG for instant page loads and zero layout shift.",
  "sw_tech4_title": "Cross-Platform Mobile Apps",
  "sw_tech4_desc": "Flutter, React Native, Swift, and Kotlin Native delivering fluid 120Hz interfaces across iOS and Android.",
  "sw_tech5_title": "Databases & Vector Search",
  "sw_tech5_desc": "PostgreSQL, ScyllaDB, Redis, Kafka distributed clusters, paired with Qdrant and pgvector for semantic search.",
  "sw_tech6_title": "Cloud Infrastructure & DevOps",
  "sw_tech6_desc": "Docker, Kubernetes, GPU Inference Clusters, Terraform, AWS, GCP, and automated CI/CD pipelines.",
  "sw_roadmap_badge": "_6-STEP DELIVERY ROADMAP/",
  "sw_roadmap_title": "Transparent End-to-End Software Engineering Process",
  "sw_roadmap_desc": "Agile/Scrum delivery with clear milestone acceptance gates, giving clients complete transparency over progress and quality.",
  "sw_step1_title": "Discovery, SRS Spec & AI Feasibility",
  "sw_step1_desc": "Business process auditing, AI feasibility analysis, architecture blueprints, and detailed data flow diagrams.",
  "sw_step2_title": "Architecture & Prototype UX/UI",
  "sw_step2_desc": "Design System prototyping, conversational AI interaction flows, security baseline, and API schemas.",
  "sw_step3_title": "Agile Sprint Delivery with AI Pair",
  "sw_step3_desc": "2-week sprints with AI-augmented pair programming accelerating delivery 2x with automated CI/CD testing.",
  "sw_step4_title": "Automated Testing, Pentesting & Audits",
  "sw_step4_desc": "Stress testing for high concurrency, OWASP Top 10 pentesting, and AI output accuracy and safety benchmarks.",
  "sw_step5_title": "Code Handover & Cloud Deployment",
  "sw_step5_desc": "Complete handover of Git repositories, Docker containers, Kubernetes deployment manifests, and operations manuals.",
  "sw_step6_title": "Warranty, 24/7 SLA & Tech Evolution",
  "sw_step6_desc": "Comprehensive system maintenance, Prometheus/Grafana monitoring, and scheduled AI model enhancements.",
  "sw_cta_eyebrow": "_INITIATE SOFTWARE PROJECT/",
  "sw_cta_title": "Bring Your Software Vision to Life with Superior Technical Rigor",
  "sw_cta_desc": "CreditBird solutions architects are ready to evaluate your requirements and craft an optimal technical blueprint from day one.",
  "sw_cta_btn": "Request Consultation & Technical Architecture Analysis",

  // Subpage: ERP
  "erp_page_title": "Kelvot ERP — Manufacturing, Warehouse WMS & Accounting | CreditBird",
  "erp_page_desc": "Kelvot ERP (kelvot.com) — Specialized bespoke ERP for manufacturing BOM, warehouse WMS, and VAS/IFRS financial accounting. Developed by CreditBird.",
  "erp_hero_eyebrow": "_INDEPENDENT ERP BRAND / KELVOT.COM",
  "erp_hero_spec": "Multi-BOM • WMS Warehousing • VAS/IFRS Accounting",
  "erp_hero_title": "Kelvot ERP — Comprehensive Manufacturing, Warehouse & Financial Management",
  "erp_hero_desc": "Specialized enterprise ERP under the CreditBird ecosystem. Bespoke-engineered for manufacturing plants, retail chains, and distribution enterprises needing real-time cash flow and production cost control.",
  "erp_hero_btn_primary": "Visit Kelvot.com Website",
  "erp_hero_btn_secondary": "Request Factory Survey & ERP Demo",
  "erp_metrics_eyebrow": "_PRODUCTION METRICS / TELEMETRY",
  "erp_metrics_title": "Rigorous quality control and operational cost minimization",
  "erp_metric1_label": "MANUFACTURING BOM",
  "erp_metric1_val": "Multi-BOM",
  "erp_metric1_sub": "Precision multi-level raw material consumption and scrap control",
  "erp_metric2_label": "WAREHOUSE ACCURACY",
  "erp_metric2_val": "99.8%",
  "erp_metric2_sub": "Zero-error Barcode/QR recognition across warehouse bin locations",
  "erp_metric3_label": "FINANCIAL REPORTING",
  "erp_metric3_val": "Real-time",
  "erp_metric3_sub": "Automated cost allocation and end-of-period cash flow journals",
  "erp_metric4_label": "ACCOUNTING COMPLIANCE",
  "erp_metric4_val": "VAS & IFRS",
  "erp_metric4_sub": "Strict compliance with Circular 200/133 and international IFRS",
  "erp_modules_eyebrow": "_CORE MODULES / ARCHITECTURE/",
  "erp_modules_title": "End-to-End ERP Architecture for Manufacturing & Commerce",
  "erp_modules_sub": "High modularity: deploy modules independently or synchronize as a unified ERP backbone.",
  "erp_modules_desc": "Each module in Kelvot ERP is built on independent microservices, ensuring real-time synchronization between financial ledgers, logistics, and shop-floor scheduling.",
  "erp_mod1_title": "Manufacturing & Multi-Level BOM Management",
  "erp_mod1_desc": "Configurable multi-level Bill of Materials, Material Requirements Planning (MRP), and stage-by-stage shop floor cost allocation.",
  "erp_mod2_title": "Smart Warehouse Management (WMS)",
  "erp_mod2_desc": "Bin location management, FIFO/FEFO expiration tracking, batch number traceability, and mobile Barcode/QR scanning.",
  "erp_mod3_title": "Managerial Accounting (VAS & IFRS)",
  "erp_mod3_desc": "Strict adherence to Circular 200/133 and IFRS standards. Automated double-entry journals triggered by inventory, purchasing, and sales events.",
  "erp_mod4_title": "Supply Chain & Centralized Procurement",
  "erp_mod4_desc": "Multi-tiered RFQ approval workflows, Purchase Order (PO) tracking, vendor rating cards, and accounts payable age analysis.",
  "erp_mod5_title": "Distribution Channel & Sales Operations",
  "erp_mod5_desc": "Dynamic pricing matrices by tier, territory, and credit limits, with automated sales volume rebate calculations.",
  "erp_mod6_title": "Automated Reconciliation & E-Invoicing",
  "erp_mod6_desc": "Bank Hub connectivity for automated bank statement reconciliation and direct compliance integration with e-invoicing providers.",
  "erp_split_eyebrow": "_SHOP-FLOOR MANUFACTURING / BOM & MRP",
  "erp_split_title": "Controlling Every Gram of Raw Material & Machine Second",
  "erp_split_desc": "Eliminate production line halts caused by material shortages and prevent excessive inventory holding costs.",
  "erp_split_link": "Explore Technical Documentation on Kelvot.com",
  "erp_bullet1_title": "Dynamic scrap rate calculation",
  "erp_bullet1_text": "Automatically factors in scrap variations based on machine batch and operator shift skill levels.",
  "erp_bullet2_title": "Automated MRP procurement planning",
  "erp_bullet2_text": "Reconciles available stock to auto-generate POs before production lines experience downtime.",
  "erp_bullet3_title": "Real-time specific cost identification",
  "erp_bullet3_text": "Precisely allocates direct raw materials, direct labor, and manufacturing overhead per unit.",
  "erp_cta_eyebrow": "_KELVOT ERP CONSULTATION/",
  "erp_cta_title": "Standardize Your Entire Business Operations Today",
  "erp_cta_desc": "ERP specialists from Kelvot and CreditBird are ready to visit your manufacturing facility, audit workflows, and map out a detailed digital roadmap.",
  "erp_cta_btn_primary": "Request Factory Audit & Commercial Quotation",
  "erp_cta_btn_secondary": "Explore Kelvot.com Website",

  // Subpage: IT Staffing
  "it_page_title": "Enterprise IT Staff Augmentation — CreditBird (Tax ID: 0315397327)",
  "it_page_desc": "Premium IT staffing services: Onsite & Dedicated Squads. Senior Engineers (Rust, Go, Python, SvelteKit, DevOps). Onboarding in 48 hours, strict B2B NDA contracts.",
  "it_hero_eyebrow": "_CORE BUSINESS ACTIVITIES / TAX ID: 0315397327",
  "it_hero_spec": "Onsite & Dedicated Squad • Onboarding in 48h • B2B NDA",
  "it_hero_title": "High-Caliber IT Staff Augmentation for Growing Enterprises",
  "it_hero_desc": "Solving senior technical recruitment challenges. We provide senior software developers, DevOps specialists, and solution architects working onsite at your office or as dedicated remote engineering squads.",
  "it_hero_btn_primary": "Request Candidate Profiles & Quotation",
  "it_hero_btn_secondary": "View 48-Hour Onboarding Process",
  "it_metrics_eyebrow": "_SERVICE SLA METRICS / STANDARDS",
  "it_metrics_title": "Rigorous vetting standards ensuring project velocity and quality",
  "it_metric1_label": "SCREENING TURNAROUND",
  "it_metric1_val": "48 Hours",
  "it_metric1_sub": "Receive pre-vetted CVs tailored to your exact technical requirements",
  "it_metric2_label": "TRIAL PERIOD",
  "it_metric2_val": "14 Days",
  "it_metric2_sub": "Evaluate performance directly in sprints with 100% free replacements",
  "it_metric3_label": "ENGINEER SENIORITY",
  "it_metric3_val": "4 - 8 Years",
  "it_metric3_sub": "Senior engineers capable of resolving complex bugs and optimizing architecture",
  "it_metric4_label": "LEGAL & INVOICING",
  "it_metric4_val": "B2B Contract",
  "it_metric4_sub": "Full VAT invoicing (Tax ID: 0315397327) and binding IP protection NDA",
  "it_models_eyebrow": "_COOPERATION MODELS / FLEXIBLE SQUADS/",
  "it_models_title": "Flexible Talent Engagement Models Tailored to Your Needs",
  "it_models_sub": "Easily scale your engineering team up or down based on project development phases.",
  "it_models_desc": "From augmenting engineers at your headquarters to establishing a dedicated Offshore Development Center (ODC).",
  "it_model1_title": "Onsite IT Engineers at Client Premises",
  "it_model1_desc": "Engineers working physically at your office, directly managed and coordinated under your internal company culture.",
  "it_model2_title": "Dedicated Remote Engineering Squad",
  "it_model2_desc": "Full-time engineers working exclusively on your codebase, supported by Tech Leads and Scrum Masters for quality governance.",
  "it_model3_title": "Sprint-Based Short-Term Augmentation",
  "it_model3_desc": "Rapidly inject vital technical talent during critical release sprints, product Go-Live dates, or architectural audits.",
  "it_model4_title": "B2B Contracts & Comprehensive NDA Protection",
  "it_model4_desc": "Full VAT commercial invoices (Tax ID: 0315397327), strict IP assignment agreements, and zero labor liability concerns.",
  "it_roles_eyebrow": "_CORE TECHNICAL ROLES / SKILLS/",
  "it_roles_title": "Senior Engineers Ready for Immediate Onboarding",
  "it_roles_sub": "Thoroughly evaluated across algorithmic problem-solving, architectural design, and communication.",
  "it_roles_desc": "We specialize in senior engineers who independently solve demanding technical challenges and mentor team members.",
  "it_role1_title": "Senior Backend Engineers",
  "it_role1_desc": "Distributed systems, high-concurrency event processing, database tuning, and banking API integrations (Rust, Go, Python, Node.js).",
  "it_role2_title": "Senior Frontend & Mobile Engineers",
  "it_role2_desc": "Fluid 60fps applications, responsive rendering optimization, and multi-platform experiences (SvelteKit, React, Flutter).",
  "it_role3_title": "DevOps & Cloud Infrastructure",
  "it_role3_desc": "Auto-scaling cloud architectures, zero-downtime CI/CD pipelines, and 24/7 infrastructure observability (Docker, K8s, AWS, Terraform).",
  "it_role4_title": "QA / Automation Test Engineers",
  "it_role4_desc": "Comprehensive automated testing suites from unit and API tests to full E2E scenarios and stress benchmarks (Playwright, Cypress, K6).",
  "it_steps_badge": "_RAPID ONBOARDING PROCESS/",
  "it_steps_title": "4 Steps to Onboard IT Engineers in 48 Hours",
  "it_steps_desc": "A streamlined process ensuring you retain full control over interviews and trial evaluations with zero financial risk.",
  "it_step1_title": "Requirement Intake & Candidate Screening",
  "it_step1_desc": "CreditBird analyzes your technical stack and delivers pre-vetted candidate profiles within 48 hours.",
  "it_step2_title": "Direct 1-on-1 Client Interview",
  "it_step2_desc": "You interview candidates directly to evaluate technical depth, problem-solving, and cultural compatibility.",
  "it_step3_title": "2-Week Hands-On Trial Evaluation",
  "it_step3_desc": "The engineer joins your sprints for 2 weeks. If expectations are not met, replacements are provided at no extra cost.",
  "it_step4_title": "B2B Service Agreement & Official Kickoff",
  "it_step4_desc": "Formal B2B service contract execution. CreditBird manages all payroll, insurance, benefits, and administrative requirements.",
  "it_cta_eyebrow": "_REINFORCE YOUR SQUAD TODAY/",
  "it_cta_title": "Augment Your Technical Team with Senior IT Engineers",
  "it_cta_desc": "CreditBird guarantees vetted engineers with proven seniority, ready to integrate into your engineering sprints within 48 hours.",
  "it_cta_btn_primary": "Get Engineering Profiles & Pricing in 48H",

  // Subpage: Scent Marketing
  "scent_page_title": "Lemy Finest — Scent Marketing & Natural Essential Oils | CreditBird",
  "scent_page_desc": "Lemy Finest (lemyfinest.com) — HVAC aroma diffusers and 100% natural essential oils with certified COA and GC-MS reports. Under the CreditBird ecosystem.",
  "scent_hero_eyebrow": "_INDEPENDENT BRAND / LEMYFINEST.COM",
  "scent_hero_spec": "Scent Marketing • HVAC Diffusers • Certified COA / GC-MS",
  "scent_hero_title": "Comprehensive Enterprise Scent Marketing Solutions",
  "scent_hero_desc": "Premium scent marketing brand under CreditBird. Providing cold-air nano diffusion systems integrated with central HVAC and 100% pure certified essential oils to create distinguished spaces and increase sales.",
  "scent_hero_btn_primary": "Visit LemyFinest.com Website",
  "scent_hero_btn_secondary": "Request Volume Survey & Olfactory Sampling",
  "scent_metrics_eyebrow": "_TECHNICAL TELEMETRY / STANDARDS",
  "scent_metrics_title": "International testing standards and advanced diffusion engineering",
  "scent_metric1_label": "COVERAGE CAPACITY",
  "scent_metric1_val": "500 - 5,000 m²",
  "scent_metric1_sub": "Direct integration into central HVAC building ventilation ducts",
  "scent_metric2_label": "DIFFUSION TECHNOLOGY",
  "scent_metric2_val": "< 0.1 µm",
  "scent_metric2_sub": "Ultra-fine suspended nano-mist droplets with zero surface condensation",
  "scent_metric3_label": "QUALITY CERTIFICATION",
  "scent_metric3_val": "100% COA",
  "scent_metric3_sub": "International Certificate of Analysis & GC-MS gas chromatography profiles",
  "scent_metric4_label": "INTELLIGENT CONTROL",
  "scent_metric4_val": "WiFi & App",
  "scent_metric4_sub": "Automated timer scheduling and hourly concentration control via mobile app",
  "scent_solutions_eyebrow": "_CORE CAPABILITIES / SOLUTIONS/",
  "scent_solutions_title": "Hardware Ecosystem & Premium Olfactory Identity",
  "scent_solutions_sub": "Engineered for spaces ranging from private executive suites to entire commercial towers.",
  "scent_solutions_desc": "Combining olfactory behavioral science with electromechanical ventilation engineering to distribute aroma consistently throughout your premises.",
  "scent_sol1_title": "Industrial Diffusers with Central HVAC Connectivity",
  "scent_sol1_desc": "Direct integration with central HVAC air handling units. Cold-air nano technology breaks oil into sub-0.1-micron droplets, covering 500 to 5,000 m² without condensation.",
  "scent_sol2_title": "Smart Standalone Diffusers for Lobbies & Showrooms",
  "scent_sol2_desc": "Refined designs for reception halls and retail showrooms from 100 to 500 m². Precise programming via WiFi/Bluetooth app for peak operational hours.",
  "scent_sol3_title": "100% Pure Natural Essential Oils (COA & GC-MS)",
  "scent_sol3_desc": "Authentically imported raw ingredients with verified Certificates of Analysis (COA) and GC-MS reports. Zero synthetic fillers or industrial alcohols.",
  "scent_sol4_title": "Bespoke Brand Signature Scents",
  "scent_sol4_desc": "Custom perfume blending creating unique signature olfactory identities that enhance brand recall and lengthen dwell time.",
  "scent_sol5_title": "Routine Maintenance & Scheduled Oil Refills",
  "scent_sol5_desc": "Full-service monthly subscription: onsite technician visits, nozzle ultrasonic cleaning, filter replacements, and scheduled oil refills.",
  "scent_sol6_title": "12 - 24 Month Warranty & Hardware Replacement",
  "scent_sol6_desc": "Factory-backed 12 to 24-month equipment warranty with immediate hardware replacement within the first 30 days for technical defects.",
  "scent_sectors_eyebrow": "_SECTORS & APPLICATIONS / DIVERSE INDUSTRIES/",
  "scent_sectors_title": "Elevating Emotional Ambience Across Diverse Commercial Spaces",
  "scent_sectors_sub": "Engage the human sensory system to cultivate deep customer brand loyalty.",
  "scent_sectors_desc": "Studies indicate customers linger up to 40% longer and demonstrate higher willingness to spend in pleasant olfactory environments.",
  "scent_sec1_title": "Hotels & Luxury Resorts",
  "scent_sec1_desc": "Welcome guests with distinguished soothing aromas from the moment they enter the grand lobby, setting a 5-star standard.",
  "scent_sec2_title": "Automotive & Luxury Real Estate Showrooms",
  "scent_sec2_desc": "Reinforce prestige, instill confidence, and facilitate decisive purchasing choices for high-value assets.",
  "scent_sec3_title": "Fashion & Premium Retail Chains",
  "scent_sec3_desc": "Define an alluring retail atmosphere, extend shopping time, and foster repeat visits from loyal clientele.",
  "scent_sec4_title": "Aesthetic Clinics, Dental Centers & Day Spas",
  "scent_sec4_desc": "Naturally neutralize medicinal odors, alleviate customer anxiety, and create a tranquil wellness retreat.",
  "scent_hvac_eyebrow": "_HVAC NANO DIFFUSION / COLD-AIR TECHNOLOGY",
  "scent_hvac_title": "Central Airflow Aroma Diffusion Architecture",
  "scent_hvac_desc": "High-velocity cold-air pressure shears essential oil molecules into particles under 0.1 microns, dispersing them through ventilation ducts without moisture.",
  "scent_hvac_link": "Explore Our Scent Library on LemyFinest.com",
  "scent_bullet1_title": "Sub-0.1 micron ultra-fine mist",
  "scent_bullet1_text": "Aerosolized molecules flow effortlessly through ventilation ducts without depositing residue on internal ductwork.",
  "scent_bullet2_title": "Intelligent IoT schedule control",
  "scent_bullet2_text": "Set automatic on/off schedules aligned with business shifts and fine-tune output per cubic meter of space.",
  "scent_bullet3_title": "Significant operational cost savings",
  "scent_bullet3_text": "Optimized oil consumption saves over 40% compared to running multiple scattered standalone diffusers.",
  "scent_cta_eyebrow": "_COMPLIMENTARY SCENT SAMPLING/",
  "scent_cta_title": "Discover the Commercial Power of Scent Marketing Today",
  "scent_cta_desc": "Lemy Finest scent consultants will bring demonstration hardware and certified oil samples directly to your venue for an onsite trial.",
  "scent_cta_btn_primary": "Request Onsite Scent Demonstration & Sampling",
  "scent_cta_btn_secondary": "Explore LemyFinest.com Website",

  // Subpage: RustSale CRM
  "rs_page_title": "RustSale CRM & Outreach Pro — Growth Operating System All-in-One | CreditBird",
  "rs_page_desc": "Native Rust Desktop Omnichannel CRM (Zalo, WhatsApp, Facebook). Microsecond execution, Local-First security, Notion documentation.",
  "rs_hero_eyebrow": "_PROPRIETARY SOFTWARE / RUST NATIVE",
  "rs_hero_spec": "Tauri v2 • Microsecond Latency • Local-First",
  "rs_hero_title": "RustSale CRM & Outreach Pro",
  "rs_hero_desc": "All-in-One growth operating system. Unifies Zalo, WhatsApp, and Facebook Messenger into a single desktop cockpit. Written in pure Rust for microsecond response times and rock-solid reliability.",
  "rs_hero_btn_primary": "View Comprehensive Guide (Notion)",
  "rs_hero_btn_secondary": "Request 1-on-1 Product Demo",
  "rs_metrics_eyebrow": "_OPERATIONAL PERFORMANCE / SYSTEM TELEMETRY",
  "rs_metrics_title": "Unrivaled advantages engineered with Native Rust",
  "rs_metric1_label": "PROCESSING SPEED",
  "rs_metric1_val": "< 1 ms",
  "rs_metric1_sub": "Microsecond latency enabled by direct machine-code compilation",
  "rs_metric2_label": "RAM FOOTPRINT",
  "rs_metric2_val": "< 45 MB",
  "rs_metric2_sub": "Consumes 90% less memory than conventional Electron desktop apps",
  "rs_metric3_label": "DATA SECURITY",
  "rs_metric3_val": "Local-First",
  "rs_metric3_sub": "Encrypted SQLite database & OS-level hardware Keyring",
  "rs_metric4_label": "INTEGRATED MODULES",
  "rs_metric4_val": "12 Modules",
  "rs_metric4_sub": "From Google Maps scraping to unified omnichannel communication",
  "rs_modules_eyebrow": "_12 INTEGRATED MODULES / PROPRIETARY SUITE/",
  "rs_modules_title": "Comprehensive Growth Operating System for B2B Sales & Marketing",
  "rs_modules_sub": "From geographic lead scraping to contract management and customer lifecycle care.",
  "rs_modules_desc": "RustSale CRM is structured with independent modules running natively on Windows, macOS, and Linux with infinite scalability.",
  "rs_mod1_title": "Command Center & Pipeline Analytics",
  "rs_mod1_desc": "Real-time monitoring of outreach velocity, lead velocity, response rates, and pipeline conversion values.",
  "rs_mod2_title": "Google Maps Lead Scraper",
  "rs_mod2_desc": "Automated regional enterprise scraping with precision extraction of phone numbers, websites, and physical addresses.",
  "rs_mod3_title": "Deduplication & Lead Normalization Engine",
  "rs_mod3_desc": "Intelligent duplicate detection, customer grouping, and automated formatting of phone and email records.",
  "rs_mod4_title": "Multi-Tiered Tagging & Audience Segmentation",
  "rs_mod4_desc": "Customizable tags and categories to segment prospects by industry, company size, and sales funnel stage.",
  "rs_mod5_title": "Omnichannel Inbox & AI Smart Reply",
  "rs_mod5_desc": "Unified Zalo, WhatsApp, and Facebook Messenger inbox with embedded AI assistant suggesting personalized sales replies.",
  "rs_mod6_title": "Multi-Fanpage Central Management",
  "rs_mod6_desc": "Connect and operate multiple Facebook pages simultaneously with automated keyword-based inbox and comment handling.",
  "rs_mod7_title": "AI Multichannel Outreach & Automation",
  "rs_mod7_desc": "Automated Zalo contact requests, sentiment classification, and autonomous agent-driven nurture sequences.",
  "rs_mod8_title": "B2B WhatsApp Messaging Campaigns",
  "rs_mod8_desc": "Send automated order updates, contract notices, and engage international partners with a 95%+ open rate.",
  "rs_mod9_title": "B2B Cold Email Nurture Engine",
  "rs_mod9_desc": "Automated multi-step email sequences with comprehensive tracking of open rates, click-throughs, and replies.",
  "rs_mod10_title": "Drag-and-Drop Kanban Sales Pipeline",
  "rs_mod10_desc": "Visualize deal progression from Lead -> Proposal -> Negotiation -> Signed Contract with fluid drag-and-drop interaction.",
  "rs_mod11_title": "Won Deals & Customer Retention",
  "rs_mod11_desc": "Secure records of closed contracts, transactional history, and automated recurring maintenance renewal schedules.",
  "rs_mod12_title": "Hardware-Grade Encrypted Keyring Vault",
  "rs_mod12_desc": "All API tokens, credentials, and local databases are encrypted on the user device for uncompromising privacy.",
  "rs_split_eyebrow": "_OMNICHANNEL INBOX / UNIFIED COMMS",
  "rs_split_title": "All Customer Conversations on a Single Screen",
  "rs_split_desc": "No more friction switching between multiple Zalo apps, browser tabs for WhatsApp, and Facebook Business Suite.",
  "rs_split_link": "Read the Omnichannel Setup Guide on Notion",
  "rs_bullet1_title": "Multi-account Zalo synchronization",
  "rs_bullet1_text": "Run personal Zalo profiles alongside Zalo Official Accounts (OA) simultaneously.",
  "rs_bullet2_title": "AI Sales Closing Assistant",
  "rs_bullet2_text": "Real-time conversation intent analysis suggesting personalized objection handling scripts.",
  "rs_bullet3_title": "WhatsApp Cloud & Web Hub",
  "rs_bullet3_text": "Seamless global communications for import-export clients and cross-border partners.",
  "rs_bullet4_title": "Centralized Facebook Fanpage inbox",
  "rs_bullet4_text": "Consolidate customer DMs and public comments across multiple pages into one queue.",
  "rs_bullet5_title": "Quick Reply response templates",
  "rs_bullet5_text": "Curated industry-specific response templates for sales and customer support representatives.",
  "rs_doc_eyebrow": "_OFFICIAL TECHNICAL DOCUMENTATION/",
  "rs_doc_title": "Comprehensive Knowledge Base on Notion",
  "rs_doc_desc": "Complete operating instructions covering Linux/Windows/macOS setup, Keyring vault configuration, and outreach scripts, updated continuously.",
  "rs_doc_btn_notion": "Open Notion Guide",
  "rs_doc_btn_github": "CreditBird GitHub",
  "rs_cta_eyebrow": "_READY TO DEPLOY/",
  "rs_cta_title": "Experience the Microsecond Speed of RustSale CRM",
  "rs_cta_desc": "Engineered and backed by CREDITBIRD TECHNOLOGY COMPANY LIMITED (Tax ID: 0315397327). Dedicated engineers ready to assist with deployment and training.",
  "rs_cta_btn_primary": "Schedule 1-on-1 Strategy & Demo Session",

  // Legal Common
  "terms_hero_eyebrow": "_LEGAL & TERMS OF SERVICE/",
  "terms_spec": "Effective Date: January 2026",
  "terms_hero_title": "Terms of Service",
  "terms_hero_desc": "Standard terms and conditions governing software development, ERP systems, IT staffing, and scent diffusion solutions provided by CREDITBIRD TECHNOLOGY COMPANY LIMITED (Tax ID: 0315397327).",
  "privacy_hero_eyebrow": "_DATA PRIVACY & SECURITY/",
  "privacy_spec": "ISO 27001 & Decree 13/2023/ND-CP",
  "privacy_hero_title": "Data Privacy Policy",
  "privacy_hero_desc": "Commitment to personal data protection, corporate data sovereignty, and technical safeguards in full compliance with Decree 13/2023/ND-CP by CREDITBIRD TECHNOLOGY CO., LTD (Tax ID: 0315397327).",
  "warranty_hero_eyebrow": "_WARRANTY & SERVICE SLA/",
  "warranty_spec": "Enterprise SLA Standards 2026",
  "warranty_hero_title": "Warranty & Service Level Agreement (SLA)",
  "warranty_hero_desc": "12-24 month hardware warranty on aroma diffusers, 100% pure COA-certified essential oils guarantee, and 99.9% uptime SLA commitments for custom software and ERP systems by CREDITBIRD TECHNOLOGY CO., LTD (Tax ID: 0315397327).",
  "security_hero_eyebrow": "_INFORMATION SECURITY STANDARDS/",
  "security_spec": "OWASP Top 10 & DevSecOps Standards",
  "security_hero_title": "Information Security & Cyber Defense Standards",
  "security_hero_desc": "Technical policies, DevSecOps pipelines, and data encryption standards governing all software, ERP, and IoT deployments by CREDITBIRD TECHNOLOGY CO., LTD (Tax ID: 0315397327).",
  "legal_toc_title": "TABLE OF CONTENTS",
  "legal_btn_partner": "Request Enterprise Partnership",
  "legal_btn_consult": "Request Service Consultation"
};

// Merge into vi and en
const viMerged = { ...viCurrent, ...viNew };
const enMerged = { ...enCurrent, ...enNew };

fs.writeFileSync(viPath, JSON.stringify(viMerged, null, 2), 'utf-8');
fs.writeFileSync(enPath, JSON.stringify(enMerged, null, 2), 'utf-8');
console.log(`Updated vi.json (${Object.keys(viMerged).length} keys)`);
console.log(`Updated en.json (${Object.keys(enMerged).length} keys)`);

// Also synchronize all other language files so they have the new keys (fallback to en/vi)
const otherLocales = ['zh', 'fr', 'hi', 'es', 'ja', 'ko', 'lo', 'th', 'ms'];

for (const loc of otherLocales) {
  const locPath = path.join(messagesDir, `${loc}.json`);
  if (!fs.existsSync(locPath)) continue;
  const current = JSON.parse(fs.readFileSync(locPath, 'utf-8'));
  // Merge en/vi fallbacks for any missing keys
  const updated: Record<string, string> = { ...enMerged, ...current };
  // Preserve schema
  updated['$schema'] = "https://inlang.com/schema/inlang-message-format";
  fs.writeFileSync(locPath, JSON.stringify(updated, null, 2), 'utf-8');
  console.log(`Synchronized ${loc}.json (${Object.keys(updated).length} keys)`);
}

console.log('Successfully completed multilingual synchronization across all files!');
